# Title         : parametric-dark.yml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/shell/vivid/themes/parametric-dark.yml
# ----------------------------------------------------------------------------
# Parametric Forge dark theme for vivid LS_COLORS with development focus

# --- Theme Metadata ----------------------------------------------------------
name: "parametric-dark"
description: "Dark theme optimized for Parametric Forge development workflow"
author: "Bardia Samiee"
version: "1.0.0"

# --- Base Colors -------------------------------------------------------------
colors:
  # Core file system objects
  normal: ""                    # Default text color
  file: ""                      # Regular files
  directory: "1;34"             # Directories (bold blue)
  symlink: "1;36"               # Symbolic links (bold cyan)
  
  # Special file types
  fifo: "40;33"                 # Named pipes (yellow on black)
  socket: "1;35"                # Sockets (bold magenta)
  door: "1;35"                  # Doors (bold magenta)
  block_device: "40;33;1"       # Block devices (bold yellow on black)
  char_device: "40;33;1"        # Character devices (bold yellow on black)
  orphan: "40;31;1"             # Orphaned symlinks (bold red on black)
  missing: "40;31;1"            # Missing files (bold red on black)
  
  # Permission-based coloring
  executable: "1;32"            # Executable files (bold green)
  setuid: "37;41"               # SUID files (white on red)
  setgid: "30;43"               # SGID files (black on yellow)
  capability: "30;41"           # Files with capabilities (black on red)
  sticky: "37;44"               # Sticky bit (white on blue)
  other_writable: "34;42"       # Other-writable (blue on green)
  sticky_other_writable: "30;42" # Sticky + other-writable (black on green)

# --- Development File Types --------------------------------------------------
development:
  # Source code files
  source_code:
    color: "1;32"               # Bold green
    extensions: [
      "c", "cpp", "cc", "cxx", "h", "hpp", "hxx",
      "rs", "go", "py", "js", "ts", "jsx", "tsx",
      "java", "kt", "swift", "rb", "php", "cs",
      "scala", "clj", "hs", "ml", "fs", "elm",
      "dart", "lua", "pl", "r", "jl", "zig", "nim"
    ]
  
  # Configuration files
  config:
    color: "1;33"               # Bold yellow
    extensions: [
      "json", "yaml", "yml", "toml", "ini", "cfg",
      "conf", "config", "xml", "plist", "env", "envrc"
    ]
  
  # Build and project files
  build:
    color: "1;35"               # Bold magenta
    extensions: ["mk", "cmake", "ninja", "bazel", "buck"]
    names: [
      "Makefile", "makefile", "GNUmakefile",
      "CMakeLists.txt", "build.gradle", "pom.xml",
      "Cargo.toml", "Cargo.lock", "package.json",
      "package-lock.json", "yarn.lock", "pyproject.toml",
      "setup.py", "requirements.txt", "Pipfile",
      "flake.nix", "flake.lock", "default.nix"
    ]
  
  # Documentation files
  docs:
    color: "1;36"               # Bold cyan
    extensions: [
      "md", "rst", "txt", "rtf", "tex", "adoc",
      "org", "wiki", "man", "1", "2", "3", "4", "5", "6", "7", "8"
    ]
    names: ["README", "CHANGELOG", "LICENSE", "COPYING", "AUTHORS"]

# --- Media File Types -------------------------------------------------------
media:
  # Image files
  images:
    color: "35"                 # Magenta
    extensions: [
      "jpg", "jpeg", "png", "gif", "bmp", "tiff", "tif",
      "svg", "webp", "ico", "heic", "heif", "raw",
      "cr2", "nef", "arw", "dng", "psd", "ai", "eps",
      "xcf", "gimp", "sketch", "fig"
    ]
  
  # Video files
  videos:
    color: "1;31"               # Bold red
    extensions: [
      "mp4", "avi", "mkv", "mov", "wmv", "flv", "webm",
      "m4v", "3gp", "ogv", "ts", "mts", "m2ts", "vob",
      "mpg", "mpeg", "divx", "xvid", "rm", "rmvb"
    ]
  
  # Audio files
  audio:
    color: "31"                 # Red
    extensions: [
      "mp3", "wav", "flac", "aac", "ogg", "wma", "m4a",
      "opus", "ape", "ac3", "dts", "aiff", "au", "mid",
      "midi", "mod", "s3m", "it", "xm"
    ]

# --- Archive and Package Files ----------------------------------------------
archives:
  color: "33"                   # Yellow
  extensions: [
    "zip", "tar", "gz", "bz2", "xz", "7z", "rar",
    "lz", "lzma", "lzo", "rz", "sz", "dz", "z",
    "Z", "jar", "war", "ear", "sar", "rar", "ace",
    "zoo", "cpio", "7z", "rz", "cab", "wim", "swm",
    "dwm", "esd", "dmg", "iso", "img", "bin", "nrg",
    "qcow", "qcow2", "qed", "vdi", "vhd", "vmdk"
  ]

# --- System and Binary Files ------------------------------------------------
system:
  # Executable files
  executables:
    color: "1;32"               # Bold green
    extensions: [
      "exe", "msi", "app", "deb", "rpm", "pkg",
      "dmg", "run", "bin", "com", "bat", "cmd",
      "ps1", "psm1", "psd1", "ps1xml", "psc1", "pssc"
    ]
  
  # System libraries
  libraries:
    color: "31"                 # Red
    extensions: [
      "so", "dylib", "dll", "a", "lib", "framework",
      "bundle", "kext", "sys", "driver", "o", "obj"
    ]
  
  # Log files
  logs:
    color: "90"                 # Bright black (gray)
    extensions: ["log", "logs", "out", "err"]

# --- Temporary and Cache Files ----------------------------------------------
temporary:
  color: "90"                   # Bright black (gray)
  extensions: [
    "tmp", "temp", "cache", "bak", "backup",
    "old", "orig", "swp", "swo", "~", "bak",
    "off", "part", "incomplete", "crdownload"
  ]
  names: [
    ".DS_Store", "Thumbs.db", "desktop.ini",
    ".localized", ".Trash", ".Trashes"
  ]

# --- Version Control Files --------------------------------------------------
vcs:
  color: "90"                   # Bright black (gray)
  names: [
    ".git", ".gitignore", ".gitattributes", ".gitmodules",
    ".svn", ".hg", ".hgignore", ".bzr", ".bzrignore",
    "CVS", ".cvsignore"
  ]
  extensions: ["patch", "diff", "orig", "rej"]

# --- Editor and IDE Files ---------------------------------------------------
editor:
  color: "90"                   # Bright black (gray)
  extensions: [
    "swp", "swo", "tmp", "~", "bak", "orig",
    "pyc", "pyo", "pyd", "__pycache__", "class",
    "elc", "fasl", "o", "obj", "exe", "com"
  ]
  names: [
    ".vscode", ".idea", ".eclipse", ".netbeans",
    ".vim", ".nvim", ".emacs.d", ".atom"
  ]

# --- Language-Specific Files ------------------------------------------------
languages:
  # Nix files
  nix:
    color: "1;34"               # Bold blue
    extensions: ["nix"]
  
  # Shell scripts
  shell:
    color: "1;32"               # Bold green
    extensions: ["sh", "bash", "zsh", "fish", "csh", "tcsh", "ksh"]
  
  # Python files
  python:
    color: "1;33"               # Bold yellow
    extensions: ["py", "pyw", "pyx", "pxd", "pxi"]
    names: ["__init__.py", "__main__.py"]
  
  # Rust files
  rust:
    color: "1;31"               # Bold red
    extensions: ["rs"]
    names: ["Cargo.toml", "Cargo.lock"]
  
  # JavaScript/TypeScript
  javascript:
    color: "1;33"               # Bold yellow
    extensions: ["js", "mjs", "cjs", "ts", "tsx", "jsx"]
  
  # Go files
  go:
    color: "1;36"               # Bold cyan
    extensions: ["go"]
    names: ["go.mod", "go.sum"]

# --- Special Directories ----------------------------------------------------
directories:
  # Development directories
  dev_dirs:
    color: "1;34"               # Bold blue
    names: [
      "src", "lib", "bin", "include", "test", "tests",
      "spec", "specs", "examples", "demo", "docs",
      "documentation", "man", "share"
    ]
  
  # Build directories
  build_dirs:
    color: "90"                 # Bright black (gray)
    names: [
      "build", "dist", "target", "out", "output",
      "node_modules", ".next", ".nuxt", "__pycache__",
      ".pytest_cache", ".coverage", ".tox", ".venv",
      "venv", "env", ".env"
    ]
  
  # Configuration directories
  config_dirs:
    color: "1;33"               # Bold yellow
    names: [
      ".config", ".local", "config", "conf",
      "etc", "settings", "preferences"
    ]
  
  # Cache directories
  cache_dirs:
    color: "90"                 # Bright black (gray)
    names: [
      ".cache", "cache", "tmp", "temp", "var",
      ".tmp", ".temp"
    ]