#!/bin/bash
# Title         : bordersrc
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/borders/bordersrc
# ----------------------------------------------------------------------------
# JankyBorders configuration with Dracula theme integration

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=0xffbd93f9   # Dracula purple - focused window
  inactive_color=0xff6272a4 # Dracula comment - unfocused windows
  ax_focus=on               # Improved compatibility with yabai/AeroSpace
)

borders "${options[@]}"
