# Title         : colima.yaml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/containers/colima.yaml
# ----------------------------------------------------------------------------
# Colima VM configuration optimized for Docker on macOS
# --- VM Resources -----------------------------------------------------------
cpu: 4 # CPU cores allocated to VM
memory: 8 # Memory in GiB
disk: 50 # Disk size in GiB (cannot be reduced after creation)
# --- Architecture & Virtualization ----------------------------------------
arch: host # Architecture: x86_64, aarch64, or host (auto-detects)
vmType: vz # vz: Apple Virtualization.framework (faster on Apple Silicon)
rosetta: true # x86 emulation on Apple Silicon (requires vz + macOS 13+)
# --- Container Runtime ----------------------------------------------------
runtime: docker # Options: docker, containerd, cri-o, incus, none
# --- Kubernetes Configuration ---------------------------------------------
kubernetes:
  enabled: false
  version: "" # k3s version (empty for latest stable)
  k3sArgs: []
  nodes: 1
  disable:
    - traefik
# --- Network Configuration ------------------------------------------------
network:
  address: true # Assign IP address to VM (required for port forwarding)
  dns: [] # Custom DNS servers (empty uses host DNS)
  dnsHosts: {} # Static DNS hosts
# --- Filesystem Mounts ----------------------------------------------------
mountType: virtiofs # Mount type: sshfs, 9p, virtiofs (fastest on macOS 13+)
mounts: # Additional mounts (home directory always mounted)
  - location: "~/Projects"
    writable: true
  - location: "~/Downloads"
    writable: false
# --- Docker Configuration -------------------------------------------------
docker: {} # Additional daemon.json settings merged with defaults
# --- SSH Configuration ----------------------------------------------------
ssh:
  loadFromHost: true # Load SSH keys from host
  forwardAgent: true # Forward SSH agent to VM
  config: {} # Custom SSH config entries
# --- Environment Variables ------------------------------------------------
env: {} # Variables set inside the VM
# --- Port Forwarding ------------------------------------------------------
portForwards: [] # Forward ports from VM to host
# --- VM Customization -----------------------------------------------------
hostname: colima
provision: [] # Provision scripts to run on VM start
