# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/system/dust/config.toml
# ----------------------------------------------------------------------------
# Directory size analyzer configuration

# --- Display Options -----------------------------------------------------
reverse = false               # Normal sort order (largest first)
display-full-paths = false    # Show relative paths for cleaner output
display-apparent-size = false # Show actual disk usage, not apparent size
no-colors = false             # Enable colors
force-colors = false          # Don't force colors (respect terminal)
no-bars = false               # Show size bars
bars-on-right = false         # Bars on left side (default)
screen-reader = false         # Normal visual output

# --- Filtering Options ---------------------------------------------------
ignore-hidden = true # Ignore dotfiles and hidden directories
only-dir = false     # Show both files and directories
only-file = false    # Show both files and directories
min-size = "1MB"     # Don't show items smaller than 1MB
depth = 3            # Default depth of 3 levels

# --- Output Options -----------------------------------------------------
output-format = "si" # Use SI units (1000) instead of binary (1024)
skip-total = false   # Show total size
output-json = false  # Normal output (not JSON)
print-errors = false # Suppress permission errors in output

# --- Performance Options -------------------------------------------------
disable-progress = false # Show progress indicator
# threads = 4                   # Number of threads (optional, defaults to system)
