# Title         : procs.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/system/procs.toml
# ----------------------------------------------------------------------------
# Procs process viewer configuration with enhanced display options, custom
# columns, and color themes for improved system monitoring and process management.

# --- Core Display Settings ---------------------------------------------------
# Basic configuration for process display and behavior

# Default columns to display (can be overridden with command-line options)
columns = [
    "pid",          # Process ID
    "user",         # Process owner
    "separator",    # Visual separator
    "tty",          # Terminal
    "usage_cpu",    # CPU usage percentage
    "usage_mem",    # Memory usage percentage
    "separator",    # Visual separator
    "state",        # Process state
    "start_time",   # Process start time
    "separator",    # Visual separator
    "command",      # Command name and arguments
]

# Process sorting configuration
sort_column = "usage_cpu"      # Default sort column
sort_order = "descending"      # Sort order: ascending, descending
numeric_search = false         # Disable numeric search by default
nonnumeric_search = true       # Enable text-based search

# --- Tree View Configuration -------------------------------------------------
# Settings for hierarchical process display

# Tree view options
tree = false                   # Disable tree view by default (enable with --tree)
tree_symbols = [
    "│",                       # Vertical line
    "├─",                      # Branch
    "└─",                      # Last branch
    "   ",                     # Spacing
]

# Process relationship display
show_parent_child = true       # Show parent-child relationships
show_thread_names = true       # Show thread names when available
show_kernel_threads = false    # Hide kernel threads by default

# --- Color Theme Configuration ------------------------------------------------
# Define colors for different process states and information types

[style]
# --- Header Colors --------------------------------------------------------
header = "bold white"          # Column headers
separator = "dim white"        # Column separators

# --- Process State Colors -------------------------------------------------
running = "green"              # Running processes
sleeping = "blue"              # Sleeping processes
waiting = "yellow"             # Waiting processes
zombie = "red"                 # Zombie processes
stopped = "magenta"            # Stopped processes
idle = "dim blue"              # Idle processes

# --- Resource Usage Colors ------------------------------------------------
# CPU usage colors (gradient from low to high)
cpu_low = "green"              # Low CPU usage (0-25%)
cpu_medium = "yellow"          # Medium CPU usage (25-75%)
cpu_high = "red"               # High CPU usage (75-100%)

# Memory usage colors (gradient from low to high)
memory_low = "green"           # Low memory usage (0-25%)
memory_medium = "yellow"       # Medium memory usage (25-75%)
memory_high = "red"            # High memory usage (75-100%)

# --- Process Information Colors -------------------------------------------
pid = "cyan"                   # Process IDs
user = "blue"                  # User names
command = "white"              # Command names
arguments = "dim white"        # Command arguments
time = "magenta"               # Time information

# --- Special Process Colors -----------------------------------------------
system_process = "dim yellow"  # System processes
user_process = "white"         # User processes
root_process = "red"           # Root processes
current_user = "bold white"    # Current user's processes

# --- Column Configuration ----------------------------------------------------
# Detailed configuration for each column type

[columns]
# --- Process Identification -----------------------------------------------
[columns.pid]
align = "right"                # Right-align process IDs
min_width = 6                  # Minimum column width
max_width = 8                  # Maximum column width

[columns.ppid]
align = "right"                # Right-align parent process IDs
min_width = 6
max_width = 8

# --- User Information ------------------------------------------------------
[columns.user]
align = "left"                 # Left-align user names
min_width = 8
max_width = 12
truncate = "middle"            # Truncate long usernames in middle

# --- Resource Usage -------------------------------------------------------
[columns.usage_cpu]
align = "right"                # Right-align CPU percentages
min_width = 6
max_width = 8
precision = 1                  # Show one decimal place

[columns.usage_mem]
align = "right"                # Right-align memory percentages
min_width = 6
max_width = 8
precision = 1                  # Show one decimal place

# --- Memory Information ---------------------------------------------------
[columns.vsize]
align = "right"                # Right-align virtual memory size
min_width = 8
max_width = 10
unit = "auto"                  # Auto-select unit (KB, MB, GB)

[columns.rss]
align = "right"                # Right-align resident set size
min_width = 8
max_width = 10
unit = "auto"                  # Auto-select unit (KB, MB, GB)

# --- Time Information ------------------------------------------------------
[columns.start_time]
align = "right"                # Right-align start times
min_width = 8
max_width = 12
format = "auto"                # Auto-format time display

[columns.elapsed_time]
align = "right"                # Right-align elapsed times
min_width = 8
max_width = 12
format = "auto"                # Auto-format time display

# --- Command Information ---------------------------------------------------
[columns.command]
align = "left"                 # Left-align command names
min_width = 20
max_width = 50
truncate = "end"               # Truncate long commands at end

[columns.command_line]
align = "left"                 # Left-align full command lines
min_width = 30
max_width = 80
truncate = "middle"            # Truncate long command lines in middle

# --- Process State Information --------------------------------------------
[columns.state]
align = "center"               # Center-align process states
min_width = 4
max_width = 6

[columns.nice]
align = "right"                # Right-align nice values
min_width = 4
max_width = 6

[columns.priority]
align = "right"                # Right-align priority values
min_width = 4
max_width = 6

# --- Terminal Information --------------------------------------------------
[columns.tty]
align = "left"                 # Left-align TTY information
min_width = 8
max_width = 12
truncate = "end"               # Truncate long TTY names

# --- Search and Filtering Configuration --------------------------------------
# Configure search and filtering behavior

[search]
# Search behavior
case_sensitive = false         # Case-insensitive search by default
regex_search = true           # Enable regex search patterns
highlight_matches = true       # Highlight search matches

# Default search columns
search_columns = [
    "command",                 # Search in command names
    "command_line",            # Search in full command lines
    "user",                    # Search in user names
]

# --- Filter Presets ----------------------------------------------------------
# Predefined filters for common use cases

[filters]
# Show only user processes (exclude system processes)
user_only = {
    exclude_users = ["root", "_system", "daemon", "_daemon"]
    exclude_commands = ["kernel_task", "launchd"]
}

# Show only high resource usage processes
high_usage = {
    min_cpu_usage = 5.0        # Minimum 5% CPU usage
    min_memory_usage = 1.0     # Minimum 1% memory usage
}

# Show only running processes
running_only = {
    states = ["running", "runnable"]
}

# Show development-related processes
development = {
    include_commands = [
        "node", "python", "cargo", "rustc", "gcc", "clang",
        "java", "javac", "go", "ruby", "php"
    ]
}

# --- Performance and Display Options -----------------------------------------
# Configure performance and display behavior

[display]
# Update and refresh settings
auto_refresh = false           # Don't auto-refresh by default
refresh_interval = 2           # Refresh every 2 seconds when enabled
max_processes = 1000           # Maximum processes to display

# Display formatting
show_header = true             # Show column headers
show_footer = false            # Don't show footer by default
show_summary = false           # Don't show process summary

# Paging and scrolling
pager = "auto"                 # Auto-detect pager: auto, less, more, none
page_size = 50                 # Number of processes per page

# --- Integration with Other Tools --------------------------------------------
# Configure integration with system tools and utilities

[integration]
# Kill command integration
kill_command = "kill"          # Command to use for killing processes
kill_signal = "TERM"           # Default signal for killing processes

# Process inspection tools
inspect_command = "ps -p"      # Command for detailed process inspection
trace_command = "strace -p"    # Command for process tracing (Linux)

# System monitoring integration
top_command = "top -p"         # Command to open process in top
htop_command = "htop -p"       # Command to open process in htop

# --- Platform-Specific Configuration -----------------------------------------
# Handle differences between macOS and Linux

[platform]
# macOS-specific settings
[platform.darwin]
# macOS process information
show_app_name = true           # Show application names on macOS
show_bundle_id = false         # Don't show bundle IDs by default
use_activity_monitor = true    # Integrate with Activity Monitor

# macOS-specific columns
additional_columns = [
    "app_name",                # Application name
    "energy_impact",           # Energy impact (macOS specific)
]

# Linux-specific settings
[platform.linux]
# Linux process information
show_cgroup = false            # Don't show cgroups by default
show_namespace = false         # Don't show namespaces by default
show_security_context = false # Don't show SELinux context

# Linux-specific columns
additional_columns = [
    "cgroup",                  # Control group
    "namespace",               # Process namespace
    "security_context",        # Security context
]

# --- Accessibility and Usability ---------------------------------------------
# Configure accessibility features and usability enhancements

[accessibility]
# Color accessibility
high_contrast = false          # Use high contrast colors
colorblind_friendly = true     # Use colorblind-friendly palette
monochrome_mode = false        # Disable colors entirely

# Text accessibility
large_text = false             # Use larger text
bold_headers = true            # Use bold headers for visibility
unicode_symbols = true         # Use Unicode symbols for tree view

# --- Logging and Debugging ---------------------------------------------------
# Configure logging and debugging features

[logging]
# Log level configuration
log_level = "warn"             # Logging level: error, warn, info, debug
log_file = "$XDG_DATA_HOME/procs/procs.log"  # Log file location
max_log_size = "10MB"          # Maximum log file size
log_rotation = true            # Enable log rotation

# Debug options
debug_mode = false             # Disable debug mode by default
verbose_output = false         # Disable verbose output
trace_execution = false        # Don't trace execution