# Title         : gitleaks.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/git/gitleaks.toml
# ----------------------------------------------------------------------------
# Gitleaks configuration extending defaults with Parametric Forge customizations

title = "Parametric Forge Gitleaks Configuration"

[extend]
# Use all default detection rules (3000+ lines of patterns)
useDefault = true

# Optionally disable overly noisy rules
# disabledRules = ["generic-api-key"]

[[allowlists]]
description = "Parametric Forge global exclusions"
paths = [
  '''\.git/''',
  '''node_modules/''',
  '''\.venv/''',
  '''result/''',
  '''\.cache/''',
  '''\.direnv/''',
  '''target/debug/''',
  '''target/release/''',
  '''\.lock$''',
  '''\.svg$''',
  '''\.png$''',
  '''\.jpg$''',
  '''\.jpeg$''',
  '''\.gif$''',
  '''\.ico$''',
  '''\.pdf$''',
]

[[allowlists]]
description = "Nix and development files"
paths = [
  '''flake\.lock$''',
  '''Cargo\.lock$''',
  '''package-lock\.json$''',
  '''yarn\.lock$''',
  '''pnpm-lock\.yaml$''',
  '''uv\.lock$''',
  '''poetry\.lock$''',
]

# Custom rules for Parametric Forge-specific patterns can be added here
# [[rules]]
# id = "forge-secret-key"
# description = "Parametric Forge secret key pattern"
# regex = '''(?i)forge[_-]?secret[\s]*[:=][\s]*['"]?([a-zA-Z0-9]{32,})['"]?'''
# keywords = ["forge", "secret"]
