# Title         : shell-enhancements.nix
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/programs/shell-enhancements.nix
# ----------------------------------------------------------------------------
# Shell enhancement tools: vivid (LS_COLORS generator) for beautiful and
# consistent file type colorization across all shell tools. Provides theme-based
# color schemes that integrate with the overall system aesthetic.

{
  config,
  lib,
  pkgs,
  ...
}:

{
  programs = {
    # --- Vivid LS_COLORS Generator ------------------------------------
    # Modern LS_COLORS generator with theme support and extensive file type coverage
    # Provides consistent colorization for ls, eza, tree, and other file listing tools
    # TODO: No home-manager module available - requires manual theme management
    
    # vivid = {
    #   enable = true;
    #   
    #   # --- Theme Configuration -------------------------------------
    #   # Default theme for LS_COLORS generation
    #   theme = "molokai";  # Options: molokai, ayu, iceberg, nord, etc.
    #   
    #   # --- Custom Theme Settings ----------------------------------
    #   # Override specific file type colors
    #   customColors = {
    #     # --- Directory Colors -----------------------------------
    #     "di" = "1;34";      # Directories (bold blue)
    #     "ln" = "1;36";      # Symbolic links (bold cyan)
    #     "or" = "1;31";      # Orphaned links (bold red)
    #     
    #     # --- File Type Colors -----------------------------------
    #     # Executable files
    #     "ex" = "1;32";      # Executables (bold green)
    #     
    #     # Archive files
    #     "*.tar" = "1;33";   # Archives (bold yellow)
    #     "*.zip" = "1;33";
    #     "*.gz" = "1;33";
    #     "*.bz2" = "1;33";
    #     "*.xz" = "1;33";
    #     
    #     # --- Development Files -------------------------------
    #     # Source code files
    #     "*.rs" = "0;33";    # Rust (yellow)
    #     "*.nix" = "0;34";   # Nix (blue)
    #     "*.py" = "0;32";    # Python (green)
    #     "*.js" = "0;35";    # JavaScript (magenta)
    #     "*.ts" = "0;35";    # TypeScript (magenta)
    #     
    #     # Configuration files
    #     "*.toml" = "0;36";  # TOML (cyan)
    #     "*.yaml" = "0;36";  # YAML (cyan)
    #     "*.yml" = "0;36";   # YAML (cyan)
    #     "*.json" = "0;36";  # JSON (cyan)
    #     
    #     # --- Media Files ---------------------------------
    #     # Image files
    #     "*.png" = "0;95";   # Images (bright magenta)
    #     "*.jpg" = "0;95";
    #     "*.jpeg" = "0;95";
    #     "*.gif" = "0;95";
    #     "*.svg" = "0;95";
    #     
    #     # Video files
    #     "*.mp4" = "0;93";   # Videos (bright yellow)
    #     "*.mkv" = "0;93";
    #     "*.avi" = "0;93";
    #     "*.mov" = "0;93";
    #     
    #     # Audio files
    #     "*.mp3" = "0;92";   # Audio (bright green)
    #     "*.flac" = "0;92";
    #     "*.wav" = "0;92";
    #     "*.ogg" = "0;92";
    #   };
    #   
    #   # --- Database Configuration ------------------------------
    #   # Custom file type database location
    #   databasePath = "${config.xdg.configHome}/vivid/filetypes.yml";
    #   
    #   # --- Integration Settings --------------------------------
    #   # Automatically set LS_COLORS environment variable
    #   setLsColors = true;
    #   
    #   # Generate colors for specific tools
    #   generateFor = [
    #     "ls"
    #     "eza"
    #     "tree"
    #     "fd"
    #     "broot"
    #   ];
    # };
  };

  # --- Environment Variables for Manual Configuration -------------------
  # These environment variables configure vivid until a home-manager module
  # is available. They should be moved to environment.nix in actual implementation.
  
  # Vivid theme and database configuration
  # VIVID_DATABASE = "${config.xdg.configHome}/vivid";
  
  # Generated LS_COLORS (this would be generated by vivid command)
  # LS_COLORS = "$(${pkgs.vivid}/bin/vivid generate molokai)";
  
  # --- Manual Configuration Commands ----------------------------------
  # These commands would be run to generate and set LS_COLORS
  # They should be integrated into shell initialization or activation scripts
  
  # Generate LS_COLORS with vivid
  # export LS_COLORS="$(vivid generate molokai)"
  
  # Alternative themes available:
  # - ayu (modern, clean theme)
  # - iceberg (blue-based theme)
  # - molokai (vim molokai inspired)
  # - nord (arctic, north-bluish theme)
  # - one-dark (atom one-dark inspired)
  # - one-light (atom one-light inspired)
  # - snazzy (hyper snazzy inspired)
  # - solarized-dark (solarized dark theme)
  # - solarized-light (solarized light theme)

  # --- Integration Notes -----------------------------------------------
  # 1. Vivid requires theme files in configs/shell/vivid/themes/
  # 2. Custom file type database can be stored in configs/shell/vivid/filetypes.yml
  # 3. LS_COLORS should be generated and exported in shell initialization
  # 4. Integration with eza, tree, fd, and other file listing tools
  # 5. Package dependency: vivid in packages/core.nix or shell-tools.nix
  # 6. Consider creating custom themes matching system color scheme
  
  # --- TODO: Future Improvements --------------------------------------
  # 1. Create custom Parametric Forge theme matching system colors
  # 2. Add support for dynamic theme switching based on terminal background
  # 3. Integrate with other color-aware tools (bat, delta, etc.)
  # 4. Create theme variants for different use cases (development, media, etc.)
  # 5. Add validation for generated LS_COLORS compatibility
  # 6. Consider integration with terminal theme management
  
  # --- Theme Integration Examples ----------------------------------
  # Example of how vivid integrates with other tools:
  
  # For eza (modern ls replacement):
  # eza uses LS_COLORS automatically when set
  
  # For tree (directory tree display):
  # tree respects LS_COLORS for file type colorization
  
  # For fd (file finder):
  # fd uses LS_COLORS for colorizing search results
  
  # For broot (directory navigator):
  # broot can be configured to use LS_COLORS in its display
}