# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/development/sqlfluff/config.toml
# ----------------------------------------------------------------------------
# SQLFluff SQL linter and formatter configuration with dialect and rules

# --- Core Settings ------------------------------------------------------------
# SQL dialect (ansi, bigquery, clickhouse, databricks, db2, duckdb, exasol, 
# hive, mysql, oracle, postgres, redshift, snowflake, soql, sparksql, sqlite, 
# teradata, tsql)
dialect = "postgres"

# Templater to use (raw, jinja, dbt, placeholder)
templater = "raw"

# Encoding for SQL files
encoding = "utf-8"

# SQL file extensions to process
sql_file_extensions = [".sql", ".SQL"]

# --- Formatting Rules -------------------------------------------------------
[rules]
# Rule configuration format: rule_code = "enable|disable|warn"

# Layout rules
"layout.long_lines" = "enable"              # L016: Line too long
"layout.trailing_whitespace" = "enable"     # L001: Trailing whitespace
"layout.indentation" = "enable"             # L003: Indentation not consistent
"layout.operators" = "enable"               # L006: Operators should be surrounded by spaces
"layout.commas" = "enable"                  # L019: Commas should be followed by whitespace
"layout.functions" = "enable"               # L017: Function name not immediately followed by parenthesis

# Capitalization rules
"capitalisation.keywords" = "enable"        # L010: Keywords must be consistently upper case
"capitalisation.identifiers" = "enable"     # L014: Unquoted identifiers must be consistently lower case
"capitalisation.functions" = "enable"       # L030: Function names must be consistently upper case
"capitalisation.literals" = "enable"        # L040: Null & Boolean literals should be upper case

# Aliasing rules
"aliasing.table" = "enable"                 # L011: Implicit/explicit aliasing of table
"aliasing.column" = "enable"                # L012: Implicit/explicit aliasing of columns
"aliasing.expression" = "enable"            # L013: Column expression without alias
"aliasing.unique" = "enable"                # L025: Alias should be unique per statement level

# Ambiguous rules
"ambiguous.distinct" = "enable"             # L015: DISTINCT used with parentheses
"ambiguous.union" = "enable"                # L020: Table aliases should be unique within each clause
"ambiguous.column_references" = "enable"    # L027: Qualified column references should be consistent

# Convention rules
"convention.not_equal" = "enable"           # L061: Use 'coalesce' instead of 'case' for null handling
"convention.select_trailing_comma" = "enable" # L031: Avoid table aliases in from clauses and join conditions
"convention.is_null" = "enable"             # L033: UNION [DISTINCT|ALL] is preferred over just UNION

# Structure rules
"structure.subquery" = "enable"             # L042: Join/From clauses should not contain subqueries
"structure.unused_cte" = "enable"           # L045: Query defines a CTE but does not use it
"structure.unnecessary_nested_case" = "enable" # L043: Unnecessary nested CASE statement

# --- Indentation Settings ---------------------------------------------------
[indentation]
# Indentation type (tab, space)
type = "space"

# Number of spaces per indentation level
width = 4

# Indent contents of brackets
indent_unit = 4

# Hanging indent for long lines
hanging_indent = 4

# Indent after comma in SELECT
comma_style = "trailing"

# --- Line Length Settings ---------------------------------------------------
[line_length]
# Maximum line length
max_line_length = 120

# Ignore comment lines for line length
ignore_comment_lines = true

# Ignore comment clauses for line length
ignore_comment_clauses = true

# --- Capitalization Settings ------------------------------------------------
[capitalisation]
# Keyword capitalization (upper, lower, capitalise, pascal)
keywords = "upper"

# Identifier capitalization (upper, lower, capitalise, pascal)
identifiers = "lower"

# Function name capitalization (upper, lower, capitalise, pascal)
functions = "upper"

# Literal capitalization (upper, lower, capitalise, pascal)
literals = "upper"

# --- Aliasing Settings ------------------------------------------------------
[aliasing]
# Table aliasing (implicit, explicit)
table = "explicit"

# Column aliasing (implicit, explicit)
column = "explicit"

# Length of table aliases
min_alias_length = 1
max_alias_length = 8

# --- Layout Settings --------------------------------------------------------
[layout]
# Spacing around operators
spacing_before_operators = true
spacing_after_operators = true

# Spacing around commas
spacing_before_commas = false
spacing_after_commas = true

# Spacing in functions
spacing_within_functions = false

# Line position of binary operators (leading, trailing)
binary_operator_position = "leading"

# --- Jinja Templating Settings ----------------------------------------------
[templater.jinja]
# Apply rules to templated sections
apply_dbt_builtins = true

# Load macros from path
load_macros_from_path = []

# Library path for custom macros
library_path = []

# Context variables
[templater.jinja.context]
# Add custom Jinja context variables here
# my_var = "my_value"

# --- DBT Templating Settings ------------------------------------------------
[templater.dbt]
# DBT project directory
project_dir = "."

# DBT profiles directory
profiles_dir = "~/.dbt"

# DBT profile name
profile = ""

# DBT target
target = ""

# --- Placeholder Templating Settings ----------------------------------------
[templater.placeholder]
# Placeholder style (colon, percent, dollar)
param_style = "colon"

# Placeholder regex pattern
param_regex = ""

# --- File Processing --------------------------------------------------------
[files]
# Exclude patterns (glob patterns)
exclude_rules = [
    "*.tmp.sql",
    "*.backup.sql",
    "migrations/*.sql",
    "seeds/*.sql"
]

# Include patterns (glob patterns)
include_rules = ["*.sql", "*.SQL"]

# Ignore files matching patterns
ignore_templated_areas = true

# --- Error Handling ---------------------------------------------------------
[errors]
# Maximum number of errors before stopping
max_errors = 0

# Ignore parsing errors
ignore_parsing_errors = false

# Ignore templating errors
ignore_templating_errors = false

# --- Output Settings --------------------------------------------------------
[output]
# Output format (human, json, yaml, github-annotation)
format = "human"

# Show statistics
show_stats = true

# Verbose output
verbose = false

# No color output
nocolor = false

# --- Diff Settings ----------------------------------------------------------
[diff]
# Include unchanged files in diff
include_unchanged = false

# Show diff context
show_context = true

# Number of context lines
context_lines = 3

# --- Fix Settings -----------------------------------------------------------
[fix]
# Force fixes even if they might be unsafe
force = false

# Show fixes that would be applied
show_fixes = true

# Apply fixes automatically
auto_fix = false

# --- Performance Settings ---------------------------------------------------
[performance]
# Number of parallel processes
processes = 1

# Disable progress bar
disable_progress_bar = false

# Bench mode for performance testing
bench = false

# --- Logging Settings -------------------------------------------------------
[logging]
# Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "INFO"

# Log file location
file = ""

# Log format
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# --- Custom Rules Configuration ---------------------------------------------
[custom_rules]
# Custom rule implementations can be configured here
# rule_name = { setting = "value" }

# --- Dialect-Specific Settings ----------------------------------------------
[dialect_settings]

# PostgreSQL-specific settings
[dialect_settings.postgres]
# Use PostgreSQL-specific functions and syntax
extended_capitalisation_policy = "upper"
unquoted_identifiers_policy = "lower"

# MySQL-specific settings
[dialect_settings.mysql]
# MySQL identifier quoting
identifier_quote_character = "`"

# BigQuery-specific settings
[dialect_settings.bigquery]
# BigQuery standard SQL mode
use_standard_sql = true

# Snowflake-specific settings
[dialect_settings.snowflake]
# Snowflake identifier handling
unquoted_identifiers_policy = "upper"

# --- Integration Settings ---------------------------------------------------
[integration]
# Git hook integration
git_hooks = true

# CI/CD integration
ci_integration = true

# Editor integration
editor_integration = true

# Pre-commit hook configuration
pre_commit = true

# --- Quality Gates ----------------------------------------------------------
[quality]
# Fail on any rule violations
fail_on_violations = true

# Warning threshold (number of warnings before failure)
warning_threshold = 0

# Error threshold (number of errors before failure)  
error_threshold = 0

# --- Exclusions -------------------------------------------------------------
[exclusions]
# Rules to exclude globally
exclude_rules = []

# Files to exclude from all checks
exclude_files = [
    "*.generated.sql",
    "*.template.sql"
]

# Directories to exclude
exclude_directories = [
    "migrations/",
    "seeds/",
    "snapshots/"
]