# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/file-managers/yazi/config.toml
# ----------------------------------------------------------------------------
# Yazi file manager configuration with themes, keybindings, and plugins

# --- Core Settings ------------------------------------------------------------
# Default sorting method (name, modified, created, size, extension)
sort_by = "name"

# Sort order (ascending, descending)
sort_reverse = false

# Sort directories first
sort_dir_first = true

# Case sensitive sorting
sort_sensitive = false

# Show hidden files by default
show_hidden = false

# Show symlink targets
show_symlink = true

# Line mode (none, size, permissions, mtime)
linemode = "size"

# --- Display Settings --------------------------------------------------------
# Use colored output
use_color = true

# Color theme
theme = "dark"

# Show file icons
show_icons = true

# Icon theme (nerd, unicode, ascii)
icon_theme = "nerd"

# Show file preview
show_preview = true

# Preview max file size (in bytes)
preview_max_size = 10485760  # 10MB

# Show borders
show_border = true

# Border style (plain, rounded, double, thick)
border_style = "rounded"

# --- Layout Configuration ---------------------------------------------------
# Layout ratio [parent, current, preview]
layout = [1, 3, 2]

# Minimum width for each pane
min_width = [10, 20, 10]

# Maximum width for each pane (0 = unlimited)
max_width = [0, 0, 0]

# Show parent directory
show_parent = true

# Show current directory header
show_header = true

# Show status bar
show_status = true

# --- Navigation Settings ----------------------------------------------------
# Wrap cursor at edges
wrap = true

# Find command case sensitivity
find_case_sensitive = false

# Find command smart case (case sensitive if uppercase present)
find_smart_case = true

# CD command follows symlinks
cd_follow_symlinks = false

# --- File Operations --------------------------------------------------------
# Confirm before delete
confirm_delete = true

# Confirm before overwrite
confirm_overwrite = true

# Move to trash instead of permanent delete
use_trash = true

# Trash directory
trash_dir = "$XDG_DATA_HOME/Trash"

# Default copy/move behavior (copy, move, link)
default_action = "copy"

# --- Preview Settings -------------------------------------------------------
# Image preview method (auto, kitty, iterm2, sixel, chafa, none)
image_preview = "auto"

# Video preview (thumbnail, none)
video_preview = "thumbnail"

# Audio preview (metadata, none)
audio_preview = "metadata"

# Archive preview (list, none)
archive_preview = "list"

# Text preview max lines
text_preview_lines = 1000

# Binary file preview (hex, none)
binary_preview = "hex"

# --- External Programs ------------------------------------------------------
[opener]
# Text files
text = [
    { run = '$EDITOR "$@"', desc = "Edit with default editor", for = "unix" },
    { run = 'code "$@"', desc = "Edit with VS Code", for = "unix" }
]

# Images
image = [
    { run = 'open "$@"', desc = "Open with default app", for = "macos" },
    { run = 'xdg-open "$@"', desc = "Open with default app", for = "linux" }
]

# Videos
video = [
    { run = 'mpv "$@"', desc = "Play with mpv", for = "unix" },
    { run = 'vlc "$@"', desc = "Play with VLC", for = "unix" }
]

# Audio
audio = [
    { run = 'mpv "$@"', desc = "Play with mpv", for = "unix" },
    { run = 'vlc "$@"', desc = "Play with VLC", for = "unix" }
]

# Archives
archive = [
    { run = 'ouch decompress "$@"', desc = "Extract with ouch", for = "unix" },
    { run = 'tar -xf "$@"', desc = "Extract with tar", for = "unix" }
]

# Documents
document = [
    { run = 'open "$@"', desc = "Open with default app", for = "macos" },
    { run = 'xdg-open "$@"', desc = "Open with default app", for = "linux" }
]

# --- Key Bindings -----------------------------------------------------------
[keymap]

# Navigation
j = "arrow -1"
k = "arrow 1"
h = "leave"
l = "enter"
g = { g = "arrow -99999999" }
G = "arrow 99999999"

# Selection
space = "select --state=none"
v = "visual_mode"
V = "visual_mode --unset"
ctrl-a = "select_all --state=true"
ctrl-r = "select_all --state=none"

# File operations
y = "yank"
x = "yank --cut"
p = "paste"
P = "paste --force"
d = "remove"
D = "remove --permanently"
c = "create"
r = "rename"
R = "rename --cursor=start"

# Search and filter
"/" = "find"
"?" = "find --previous"
n = "find_arrow"
N = "find_arrow --previous"
f = "filter"
F = "filter --smart"

# View options
z = { h = "hidden toggle", s = "sort", t = "linemode" }
"." = "hidden toggle"
s = "sort"
S = "sort --reverse"
t = "tab_create"
T = "tab_close"

# Bookmarks
m = "bookmark"
"'" = "bookmark --goto"

# System
q = "quit"
Q = "quit --no-cwd-file"
"!" = "shell"
":" = "shell --block"

# Help
"?" = "help"

# --- Mouse Support ----------------------------------------------------------
[mouse]
# Enable mouse support
enabled = true

# Click to select
click_select = true

# Double click to enter
double_click_enter = true

# Right click context menu
right_click_menu = true

# Scroll sensitivity
scroll_lines = 3

# --- Plugins -----------------------------------------------------------------
[plugin]
# Plugin directory
dir = "$XDG_CONFIG_HOME/yazi/plugins"

# Auto-load plugins
auto_load = true

# Enabled plugins
enabled = [
    "git",
    "archive",
    "image",
    "video"
]

# Plugin settings
[plugin.git]
# Show git status in file list
show_status = true

# Git status symbols
symbols = { modified = "M", added = "A", deleted = "D", renamed = "R", untracked = "?" }

[plugin.archive]
# Supported archive formats
formats = ["zip", "tar", "gz", "bz2", "xz", "7z", "rar"]

# Preview archive contents
preview = true

[plugin.image]
# Image preview quality (low, medium, high)
quality = "medium"

# Cache image previews
cache = true

# Cache directory
cache_dir = "$XDG_CACHE_HOME/yazi/images"

[plugin.video]
# Generate video thumbnails
thumbnails = true

# Thumbnail cache directory
cache_dir = "$XDG_CACHE_HOME/yazi/videos"

# --- Theme Configuration ----------------------------------------------------
[theme]
# Color scheme
scheme = "dark"

# File type colors
[theme.filetype]
# Directories
dir = { fg = "blue", bold = true }
link = { fg = "cyan" }
link_broken = { fg = "red", crossed = true }

# Executables
exec = { fg = "green", bold = true }

# Archives
archive = { fg = "yellow" }

# Images
image = { fg = "magenta" }

# Videos
video = { fg = "red" }

# Audio
audio = { fg = "red" }

# Documents
document = { fg = "cyan" }

# Code files
code = { fg = "green" }

# Configuration files
config = { fg = "yellow" }

# Temporary files
temp = { fg = "gray" }

# Hidden files
hidden = { fg = "gray", dim = true }

# --- Status Bar Configuration -----------------------------------------------
[status]
# Show file count
show_count = true

# Show selection count
show_selection = true

# Show disk usage
show_disk_usage = true

# Show current path
show_path = true

# Show permissions
show_permissions = true

# Show file size
show_size = true

# Show modification time
show_mtime = true

# --- Integration Settings ---------------------------------------------------
[integration]
# Shell integration
shell = "$SHELL"

# Terminal integration
terminal = "$TERM"

# Editor integration
editor = "$EDITOR"

# Pager integration
pager = "$PAGER"

# File manager integration
file_manager = "yazi"

# --- Performance Settings ---------------------------------------------------
[performance]
# Number of worker threads
workers = 4

# Cache size (number of entries)
cache_size = 1000

# Preview cache size (MB)
preview_cache_size = 100

# Lazy loading
lazy_loading = true

# --- Security Settings ------------------------------------------------------
[security]
# Confirm dangerous operations
confirm_dangerous = true

# Sandbox external commands
sandbox_commands = false

# Maximum file size for preview (bytes)
max_preview_size = 52428800  # 50MB

# --- Logging Settings -------------------------------------------------------
[log]
# Log level (error, warn, info, debug, trace)
level = "info"

# Log file location
file = "$XDG_DATA_HOME/yazi/yazi.log"

# Maximum log file size (MB)
max_size = 10

# Number of log files to keep
max_files = 5

# --- Advanced Settings ------------------------------------------------------
[advanced]
# Update check
check_updates = true

# Telemetry
telemetry = false

# Crash reporting
crash_reports = false

# Memory limit (MB)
memory_limit = 500