# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/git/gitui/config.toml
# ----------------------------------------------------------------------------
# GitUI terminal Git interface configuration with themes and keybindings

# --- Core Settings ------------------------------------------------------------
# Default tab to show on startup (status, log, stashing, stashlist, files)
tab = "status"

# Confirm before quit
confirm_quit = true

# Show untracked files in status
show_untracked_files = true

# Show ignored files in status
show_ignored_files = false

# Auto-refresh interval in seconds (0 = disabled)
auto_refresh = 5

# Maximum number of commits to load in log
max_log_commits = 1000

# --- Display Settings --------------------------------------------------------
# Use mouse support
mouse_support = true

# Show line numbers in diff view
show_line_numbers = true

# Tab size for displaying files
tab_size = 4

# Wrap long lines in diff view
wrap_lines = false

# Show whitespace in diff
show_whitespace = false

# Syntax highlighting in diff
syntax_highlighting = true

# --- Performance Settings ---------------------------------------------------
# Number of worker threads for background operations
worker_threads = 4

# Cache size for file diffs
diff_cache_size = 100

# Lazy loading for large repositories
lazy_loading = true

# --- External Tools ----------------------------------------------------------
# External editor command
editor = "$EDITOR"

# External diff tool
diff_tool = ""

# External merge tool
merge_tool = ""

# Shell command
shell = "$SHELL"

# --- Key Bindings -----------------------------------------------------------
[keys]

# Global keys
quit = "q"
force_quit = "Q"
refresh = "F5"
help = "?"
toggle_mouse = "m"

# Navigation
up = "k"
down = "j"
left = "h"
right = "l"
page_up = "ctrl+b"
page_down = "ctrl+f"
home = "g"
end = "G"
tab_next = "tab"
tab_prev = "shift+tab"

# Status tab
stage_item = "space"
stage_all = "a"
unstage_item = "u"
unstage_all = "U"
ignore_item = "i"
commit = "c"
amend = "A"
reset_item = "r"
reset_all = "R"
stash = "s"
stash_pop = "p"

# Files tab
open_file = "enter"
edit_file = "e"
delete_file = "d"
rename_file = "n"

# Log tab
show_commit = "enter"
checkout_commit = "c"
create_branch = "b"
create_tag = "t"
reset_to_commit = "r"
revert_commit = "v"

# Stash tab
apply_stash = "a"
pop_stash = "p"
drop_stash = "d"
show_stash = "enter"

# Branch tab
checkout_branch = "enter"
create_branch = "c"
delete_branch = "d"
rename_branch = "r"
merge_branch = "m"
rebase_branch = "R"

# Remote tab
fetch = "f"
pull = "p"
push = "P"

# --- Theme Configuration ----------------------------------------------------
[theme]
# Color scheme (dark, light, custom)
scheme = "dark"

# Custom colors (when scheme = "custom")
[theme.colors]
# Background colors
bg_primary = "#1e1e1e"
bg_secondary = "#252526"
bg_tertiary = "#2d2d30"

# Foreground colors
fg_primary = "#cccccc"
fg_secondary = "#969696"
fg_tertiary = "#6a6a6a"

# Accent colors
accent_primary = "#007acc"
accent_secondary = "#0e639c"

# Status colors
success = "#4ec9b0"
warning = "#ffcc02"
error = "#f44747"
info = "#75beff"

# Git status colors
added = "#4ec9b0"
modified = "#ffcc02"
deleted = "#f44747"
renamed = "#c586c0"
untracked = "#969696"
ignored = "#6a6a6a"
conflicted = "#f44747"

# Diff colors
diff_add = "#4ec9b0"
diff_delete = "#f44747"
diff_modify = "#ffcc02"
diff_header = "#569cd6"
diff_hunk = "#c586c0"

# UI element colors
border = "#3c3c3c"
selection = "#264f78"
cursor = "#ffffff"
scrollbar = "#424242"

# Syntax highlighting colors
keyword = "#569cd6"
string = "#ce9178"
comment = "#6a9955"
number = "#b5cea8"
operator = "#d4d4d4"
function = "#dcdcaa"
variable = "#9cdcfe"
type = "#4ec9b0"

# --- Diff Settings ----------------------------------------------------------
[diff]
# Context lines around changes
context_lines = 3

# Show function names in diff headers
show_function_names = true

# Algorithm for diff generation (myers, patience, histogram)
algorithm = "myers"

# Ignore whitespace changes
ignore_whitespace = false

# Ignore whitespace at end of lines
ignore_whitespace_eol = false

# Ignore changes in amount of whitespace
ignore_whitespace_change = false

# Ignore blank lines
ignore_blank_lines = false

# --- Commit Settings --------------------------------------------------------
[commit]
# Default commit message template
template = ""

# Sign commits by default
sign_commits = false

# GPG key for signing
gpg_key = ""

# Commit message length limits
subject_length_limit = 50
body_length_limit = 72

# Show commit message length indicators
show_length_indicators = true

# Auto-wrap commit messages
auto_wrap = true

# --- Branch Settings --------------------------------------------------------
[branch]
# Default branch name for new repositories
default_name = "main"

# Show remote tracking branches
show_remote_branches = true

# Show stale remote branches
show_stale_branches = false

# Auto-setup remote tracking
auto_setup_remote = true

# --- Stash Settings ---------------------------------------------------------
[stash]
# Include untracked files in stash
include_untracked = true

# Include ignored files in stash
include_ignored = false

# Default stash message
default_message = "WIP: stashed changes"

# --- Log Settings -----------------------------------------------------------
[log]
# Show merge commits
show_merges = true

# Show commit graph
show_graph = true

# Show commit signatures
show_signatures = false

# Date format for commits (relative, short, iso, rfc, raw)
date_format = "relative"

# Author format (name, email, both)
author_format = "name"

# --- Remote Settings --------------------------------------------------------
[remote]
# Default remote name
default_name = "origin"

# Auto-fetch on startup
auto_fetch = false

# Fetch interval in minutes (0 = disabled)
fetch_interval = 0

# Show remote URLs
show_urls = true

# --- File Settings ----------------------------------------------------------
[files]
# Show binary files in file list
show_binary = false

# Maximum file size to show diff (in bytes)
max_diff_size = 1048576  # 1MB

# File extensions to treat as binary
binary_extensions = [
    "exe", "dll", "so", "dylib", "bin", "obj",
    "jpg", "jpeg", "png", "gif", "bmp", "ico",
    "mp3", "mp4", "avi", "mov", "pdf", "zip"
]

# --- Search Settings --------------------------------------------------------
[search]
# Case sensitive search
case_sensitive = false

# Use regex in search
use_regex = false

# Whole word search
whole_word = false

# Search in commit messages
search_commits = true

# Search in file contents
search_files = true

# --- Integration Settings ---------------------------------------------------
[integration]
# Shell completion
shell_completion = true

# Git hooks integration
git_hooks = true

# External tool integration
external_tools = true

# Clipboard integration
clipboard = true

# --- Advanced Settings ------------------------------------------------------
[advanced]
# Git command timeout in seconds
git_timeout = 30

# Maximum number of files to show in status
max_status_files = 1000

# Use libgit2 instead of git command
use_libgit2 = false

# Enable experimental features
experimental = false

# --- Logging Settings -------------------------------------------------------
[logging]
# Log level (error, warn, info, debug, trace)
level = "info"

# Log file location
file = "$XDG_DATA_HOME/gitui/gitui.log"

# Maximum log file size (MB)
max_size = 10

# Number of log files to keep
max_files = 5

# --- Performance Tuning -----------------------------------------------------
[performance]
# Disable file system watching for large repos
disable_fs_watch = false

# Threshold for large repository (number of files)
large_repo_threshold = 10000

# Use sparse checkout for large repos
use_sparse_checkout = false

# Limit diff calculation for large files
diff_size_limit = 10485760  # 10MB

# --- Accessibility ----------------------------------------------------------
[accessibility]
# High contrast mode
high_contrast = false

# Larger text mode
large_text = false

# Screen reader support
screen_reader = false

# Reduced motion
reduced_motion = false