# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/network/gping/config.toml
# ----------------------------------------------------------------------------
# gping ping visualization configuration with graphs and monitoring

# --- Core Settings ------------------------------------------------------------
# Default ping interval in seconds
interval = 1.0

# Default ping timeout in seconds
timeout = 5.0

# Number of ping packets to send (0 = unlimited)
count = 0

# Packet size in bytes
packet_size = 64

# Time to live (TTL) for packets
ttl = 64

# --- Display Settings --------------------------------------------------------
# Use colored output
colored_output = true

# Color theme (auto, dark, light)
color_theme = "dark"

# Graph height in terminal rows
graph_height = 10

# Graph width in terminal columns (0 = auto)
graph_width = 0

# Show statistics
show_stats = true

# Show timestamps
show_timestamps = true

# Update frequency for display (Hz)
refresh_rate = 10

# --- Graph Configuration ----------------------------------------------------
# Graph type (line, bar, scatter)
graph_type = "line"

# Graph scale (auto, fixed)
scale_type = "auto"

# Fixed scale maximum (milliseconds, only used with fixed scale)
scale_max = 100

# Show grid lines
show_grid = true

# Show axis labels
show_labels = true

# Show legend
show_legend = true

# Graph smoothing (0.0 = no smoothing, 1.0 = maximum smoothing)
smoothing = 0.1

# --- Color Theme Configuration -----------------------------------------------
[colors.dark]
# Response time colors (gradient based on latency)
latency_excellent = "green"      # < 10ms
latency_good = "bright_green"    # 10-50ms
latency_fair = "yellow"          # 50-100ms
latency_poor = "red"             # 100-200ms
latency_bad = "bright_red"       # > 200ms

# Packet loss colors
no_loss = "green"
low_loss = "yellow"              # < 5%
medium_loss = "red"              # 5-20%
high_loss = "bright_red"         # > 20%

# Graph elements
graph_line = "cyan"
graph_fill = "blue"
graph_grid = "gray"
graph_axis = "white"
graph_labels = "bright_white"

# Statistics colors
stats_min = "green"
stats_avg = "yellow"
stats_max = "red"
stats_loss = "bright_red"
stats_jitter = "magenta"

# UI elements
border = "gray"
title = "bright_white"
timestamp = "gray"
legend = "white"

[colors.light]
# Light theme for bright terminals
latency_excellent = "dark_green"
latency_good = "green"
latency_fair = "dark_yellow"
latency_poor = "dark_red"
latency_bad = "red"

no_loss = "dark_green"
low_loss = "dark_yellow"
medium_loss = "dark_red"
high_loss = "red"

graph_line = "dark_cyan"
graph_fill = "dark_blue"
graph_grid = "gray"
graph_axis = "black"
graph_labels = "black"

stats_min = "dark_green"
stats_avg = "dark_yellow"
stats_max = "dark_red"
stats_loss = "red"
stats_jitter = "dark_magenta"

border = "gray"
title = "black"
timestamp = "gray"
legend = "black"

# --- Statistics Configuration -----------------------------------------------
# Statistics window size (number of samples)
stats_window = 100

# Calculate jitter (standard deviation of latency)
calculate_jitter = true

# Calculate packet loss percentage
calculate_loss = true

# Show percentile statistics
show_percentiles = true

# Percentiles to calculate
percentiles = [50, 90, 95, 99]

# --- Alert Configuration ---------------------------------------------------
# Enable alerts for high latency
enable_latency_alerts = false

# Latency alert threshold (milliseconds)
latency_alert_threshold = 100

# Enable alerts for packet loss
enable_loss_alerts = false

# Packet loss alert threshold (percentage)
loss_alert_threshold = 5

# Alert sound (if supported by terminal)
alert_sound = false

# Alert command to execute
alert_command = ""

# --- Logging Settings -------------------------------------------------------
# Enable logging to file
enable_logging = false

# Log file location
log_file = "$XDG_DATA_HOME/gping/ping.log"

# Log format (text, json, csv)
log_format = "text"

# Log level (error, warn, info, debug)
log_level = "info"

# Rotate log files
rotate_logs = true

# Maximum log file size (MB)
max_log_size = 10

# Number of log files to keep
max_log_files = 5

# --- Network Configuration --------------------------------------------------
# Source IP address for pings
source_ip = ""

# Network interface to use
interface = ""

# Use IPv4 only
ipv4_only = false

# Use IPv6 only
ipv6_only = false

# Don't fragment packets
dont_fragment = false

# --- Advanced Settings ------------------------------------------------------
# Buffer size for network operations
buffer_size = 8192

# Socket priority (0-7, Linux only)
socket_priority = 0

# Type of Service (ToS) field
tos = 0

# Traffic class (IPv6)
traffic_class = 0

# --- Multi-Target Configuration ---------------------------------------------
# Enable multi-target mode
multi_target = false

# Maximum number of concurrent targets
max_targets = 10

# Layout for multi-target display (grid, list, tabs)
multi_layout = "grid"

# Grid columns for multi-target display
grid_columns = 2

# --- Performance Settings ---------------------------------------------------
# Number of worker threads
worker_threads = 4

# Queue size for ping results
result_queue_size = 1000

# Memory limit for graph data (MB)
memory_limit = 100

# Data retention period (seconds)
data_retention = 3600

# --- Export Settings --------------------------------------------------------
# Export format (json, csv, xml)
export_format = "json"

# Export file location
export_file = ""

# Include raw data in export
export_raw_data = true

# Export interval (seconds, 0 = export at end)
export_interval = 0

# --- Integration Settings ---------------------------------------------------
[integration]
# Shell completion support
enable_completions = true

# External commands
[integration.commands]
# Command to resolve hostnames
resolve_command = "nslookup"

# Command to trace route
traceroute_command = "traceroute"

# Command to show network interfaces
interface_command = "ifconfig"

# --- Monitoring Profiles ----------------------------------------------------
# Predefined configurations for different monitoring scenarios
[profiles.quick]
interval = 0.5
count = 10
graph_height = 5
show_stats = false

[profiles.detailed]
interval = 1.0
count = 0
graph_height = 15
show_stats = true
calculate_jitter = true
show_percentiles = true

[profiles.continuous]
interval = 5.0
count = 0
enable_logging = true
log_format = "csv"
data_retention = 86400  # 24 hours

[profiles.alert]
interval = 1.0
enable_latency_alerts = true
latency_alert_threshold = 50
enable_loss_alerts = true
loss_alert_threshold = 1

# --- Keyboard Shortcuts ----------------------------------------------------
[keybindings]
# Navigation
quit = "q"
pause = "p"
reset = "r"
help = "h"

# Display toggles
toggle_stats = "s"
toggle_grid = "g"
toggle_legend = "l"
toggle_timestamps = "t"

# Scale controls
scale_up = "+"
scale_down = "-"
auto_scale = "a"

# Export and logging
export_data = "e"
toggle_logging = "L"

# --- Platform-Specific Settings ---------------------------------------------
# macOS-specific settings
[macos]
# Use system ping command
use_system_ping = false

# Privilege escalation method
privilege_method = "sudo"

# Linux-specific settings
[linux]
# Use raw sockets (requires root)
use_raw_sockets = false

# Capability requirements
required_capabilities = ["CAP_NET_RAW"]

# Windows-specific settings
[windows]
# Use ICMP.dll
use_icmp_dll = true

# Privilege requirements
require_admin = false