# Title         : core-navigation.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/packages/core-navigation.toml
# ----------------------------------------------------------------------------
# Essential file manager navigation and movement functionality

# --- Smart Movement & Entry ----------------------------------------------
# Smart enter - intelligently handle enter key based on file type
[[plugin.deps]]
use = "yazi-rs/plugins:smart-enter"

# Bypass - Skip single-subdirectory folders automatically
[[plugin.deps]]
use = "Rolv-Apneseth/bypass.yazi"

# Fast enter - Auto-decompress archives and enter deepest directory
[[plugin.deps]]
use = "ourongxing/fast-enter.yazi"

# Augment command - Enhanced built-in commands with smart defaults
[[plugin.deps]]
use = "hankertrix/augment-command.yazi"

# --- Vim-Style Movement ---------------------------------------------------
# Relative motions - Vim-style numbered motions (3j, 5k, etc.)
[[plugin.deps]]
use = "yazi-rs/plugins:relative-motions"

# Jump to char - Vim-like f<char> navigation
[[plugin.deps]]
use = "yazi-rs/plugins:jump-to-char"

# --- Filtering & Search ---------------------------------------------------
# Smart filter - Continuous filtering with auto-directory entry
[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"

# Search jump - Flash.nvim-like jumping in file manager
[[plugin.deps]]
use = "DreamMaoMao/searchjump.yazi"

# Easy jump - Hop.nvim-style visual jumping with character labels
[[plugin.deps]]
use = "mikavilpas/easyjump.yazi"

# --- Enhanced Search Tools ------------------------------------------------
# Note: Using native fzf integration via system fzf package

# Directory history - Fuzzy search through navigation history
[[plugin.deps]]
use = "bulletmark/cdhist.yazi"

# Zoxide integration - Smart directory jumping
[[plugin.deps]]
use = "DreamMaoMao/keyjump.yazi"

# --- Clipboard & Paste Operations -----------------------------------------
# Smart paste - Context-aware paste into hovered directories
[[plugin.deps]]
use = "yazi-rs/plugins:smart-paste"

# --- Session Management ---------------------------------------------------
# Session - Cross-instance state synchronization
[[plugin.deps]]
use = "yazi-rs/plugins:session"

# Command palette - Fuzzy searchable keybinds
[[plugin.deps]]
use = "Mr-Ples/command-palette.yazi"

# Advanced bookmarks - Directory history, fuzzy search, path truncation
[[plugin.deps]]
use = "WhoSowSee/whoosh.yazi"

# Simple tagging - Cross-platform file tagging system
[[plugin.deps]]
use = "boydaihungst/simple-tag.yazi"
