# Title         : media-preview.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/packages/media-preview.toml
# ----------------------------------------------------------------------------
# Comprehensive preview enhancements for all file types

# --- Directory & Archive Previewers --------------------------------------
# Directory preview with eza - Enhanced directory listing
[[plugin.deps]]
use = "ahkohd/eza-preview.yazi"

# Archive preview with lsar - Better than basic archive preview
[[plugin.deps]]
use = "yazi-rs/plugins:lsar"

# --- Document Previewers -------------------------------------------------
# Markdown preview with glow - Beautiful markdown rendering
[[plugin.deps]]
use = "Reledia/glow.yazi"

# Note: Ape/rich-preview.yazi does not exist - removed for now

# Pandoc preview - Universal document converter for various formats
[[plugin.deps]]
use = "Junker/pandoc.yazi"

# EPUB preview - E-book preview with covers and metadata
[[plugin.deps]]
use = "kirasok/epub-preview.yazi"

# --- Specialized Document Formats ----------------------------------------
# Jupyter notebook preview - Data science workflows
[[plugin.deps]]
use = "AnirudhG07/nbpreview.yazi"

# Comic book archives - Preview CBZ/CBR files
[[plugin.deps]]
use = "navysky12/comicthumb.yazi"

# DjVu documents - Preview DjVu format files
[[plugin.deps]]
use = "Shallow-Seek/djvu-view.yazi"

# Torrent files - Preview torrent contents
[[plugin.deps]]
use = "kirasok/torrent-preview.yazi"

# --- Code & Text Previewers ----------------------------------------------
# Hex viewer - Binary file preview
[[plugin.deps]]
use = "Reledia/hexyl.yazi"

# Bat preview - Enhanced code highlighting with themes
[[plugin.deps]]
use = "mgumz/yazi-plugin-bat"

# PCAP preview - Network capture file analysis
[[plugin.deps]]
use = "mgumz/yazi-plugin-pcap"

# File metadata - Rich file information display
[[plugin.deps]]
use = "boydaihungst/file-extra-metadata.yazi"

# Compressed text preview - View .gz, .bz2, .xz without extraction
[[plugin.deps]]
use = "vmikk/zless-preview.yazi"

# --- Media Previewers -----------------------------------------------------
# Enhanced media info - Rich metadata for audio/video (newer, maintained)
[[plugin.deps]]
use = "boydaihungst/mediainfo.yazi"

# Audio metadata with exiftool - Detailed audio file info
[[plugin.deps]]
use = "Sonico98/exifaudio.yazi"

# Video thumbnails - Faster video preview generation
[[plugin.deps]]
use = "ze0987/ffmpegthumbnailer.yazi"

# --- Image Previewers -----------------------------------------------------
# Image zoom - Magnify images for detailed viewing
[[plugin.deps]]
use = "yazi-rs/plugins:zoom"

# Modern image formats - HEIC, AVIF, JXL support
[[plugin.deps]]
use = "yazi-rs/plugins:piper"

# --- Data Previewers -----------------------------------------------------
# CSV/TSV data preview with miller - Structured data viewing
[[plugin.deps]]
use = "Reledia/miller.yazi"

# DuckDB for SQL-based data preview - Parquet/CSV/JSON analysis
[[plugin.deps]]
use = "wylie102/duckdb.yazi"
