# Title         : system-integration.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/packages/system-integration.toml
# ----------------------------------------------------------------------------
# System integration: remote operations, clipboard, shell, and utilities

# --- Remote Operations ----------------------------------------------------
# SSHFS - Mount remote directories directly in yazi  
[[plugin.deps]]
use = "uhs-robert/sshfs.yazi"

# Rsync - Local and remote sync operations
[[plugin.deps]]
use = "yazi-rs/plugins:rsync"

# --- Clipboard Operations ------------------------------------------------
# System clipboard - Cross-platform clipboard integration
[[plugin.deps]]
use = "orhnk/system-clipboard.yazi"

# --- File Recovery & Trash Management ------------------------------------
# Restore - Restore/recover deleted files from trash
[[plugin.deps]]
use = "boydaihungst/restore.yazi"

# Recycle bin - Enhanced trash management with age-based cleanup
[[plugin.deps]]
use = "uhs-robert/recycle-bin.yazi"

# --- Command & Shell Utilities --------------------------------------------
# Open with command - Open files using custom prompted commands
[[plugin.deps]]
use = "Ape/open-with-cmd.yazi"

# Command prompt - Execute Yazi commands via prompt interface
[[plugin.deps]]
use = "KKV9/command.yazi"

# Custom shell - Run shell commands with better integration
[[plugin.deps]]
use = "AnirudhG07/custom-shell.yazi"

# --- Utilities ------------------------------------------------------------
# Directory size calculator - Show sizes of selected items
[[plugin.deps]]
use = "pirafrank/what-size.yazi"
