# Parametric Forge Pandoc Defaults
# Path: ~/.local/share/pandoc/defaults/
# Common document conversion settings
metadata:
    author: "Bardia Samiee"
    lang: "en-US"
# Input/Output
from: markdown
to: html5
# HTML-specific options
html-math-method: mathjax
self-contained: true
# Syntax highlighting
highlight-style: github
# Table of contents
toc: true
toc-depth: 4
# Document structure
section-divs: true
include-in-header: []
include-before-body: []
include-after-body: []
# Variables
variables:
    geometry: margin=1in
    fontsize: 11pt
    linestretch: 1.2
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
