# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ast-grep-upstream = {
    pname = "ast-grep-upstream";
    version = "0.45.0";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "ast-grep";
      rev = "0.45.0";
      fetchSubmodules = false;
      sha256 = "sha256-njMkegbthIvJAI0tlSVg1G+/wRwSqWwXu4ZjM216Lys=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-njMkegbthIvJAI0tlSVg1G+_wRwSqWwXu4ZjM216Lys=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  biome-aarch64-darwin = {
    pname = "biome-aarch64-darwin";
    version = "2.5.5";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.5/biome-darwin-arm64";
      sha256 = "sha256-YHLWjTpPr3TCgCwQZlSQTyBS+FZ1o9FjIhPdl3pLZLs=";
    };
  };
  biome-aarch64-linux = {
    pname = "biome-aarch64-linux";
    version = "2.5.5";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.5/biome-linux-arm64-musl";
      sha256 = "sha256-D0h8KOyiyH4Ot5tzrYTJ/Au6tqbPNRP1/tvHTvLKLQs=";
    };
  };
  biome-x86_64-linux = {
    pname = "biome-x86_64-linux";
    version = "2.5.5";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.5/biome-linux-x64-musl";
      sha256 = "sha256-VJ/qJ8dCEqrrLHNzRgKPrLzKepP2bPSqFFOI3YsY17w=";
    };
  };
  duckdb-aarch64-darwin = {
    pname = "duckdb-aarch64-darwin";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-osx-universal.zip";
      sha256 = "sha256-ekvDqT9/kvW0DNCcIa+vmOQVxsudkXAGSZN4LnefQRU=";
    };
  };
  duckdb-aarch64-linux = {
    pname = "duckdb-aarch64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-arm64.zip";
      sha256 = "sha256-AhYxlwJ6QhSRRzZNMfpnysghCFF6S+QzBKHMIm6u8Ho=";
    };
  };
  duckdb-x86_64-linux = {
    pname = "duckdb-x86_64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-amd64.zip";
      sha256 = "sha256-CMDKEXER/O3hQjnQCTeSNSvv3BdCGMNE0jLBMnlkPQU=";
    };
  };
  nodejs-bin_26-aarch64-darwin = {
    pname = "nodejs-bin_26-aarch64-darwin";
    version = "26.5.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.5.0/node-v26.5.0-darwin-arm64.tar.xz";
      sha256 = "sha256-SCMdYgTspr4T5sUYTf3/odZK2IiANkzCz7GY+HLLKxM=";
    };
  };
  nodejs-bin_26-aarch64-linux = {
    pname = "nodejs-bin_26-aarch64-linux";
    version = "26.5.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.5.0/node-v26.5.0-linux-arm64.tar.xz";
      sha256 = "sha256-A23wtJZi67NQ61bxysYDaZsentHiYD7hKf79pHNHkDA=";
    };
  };
  nodejs-bin_26-x86_64-linux = {
    pname = "nodejs-bin_26-x86_64-linux";
    version = "26.5.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.5.0/node-v26.5.0-linux-x64.tar.xz";
      sha256 = "sha256-n2GVKPHbXdxB3M9UIRBm+0IijWmhVnM8acudbMkuNYw=";
    };
  };
  pnpm_11 = {
    pname = "pnpm_11";
    version = "11.17.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-11.17.0.tgz";
      sha256 = "sha256-ZE61B5ZU6H2uWaB+YtfwmBYrnOWPBgdzKLXd78ochUE=";
    };
  };
  sqlean-aarch64-darwin = {
    pname = "sqlean-aarch64-darwin";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-macos-arm64.zip";
      sha256 = "sha256-G8qhU4xCuw0qXQhkkJqvV0dbDiuow4BwVXeQsOxaeFo=";
    };
  };
  sqlean-aarch64-linux = {
    pname = "sqlean-aarch64-linux";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-linux-arm64.zip";
      sha256 = "sha256-B02nNIeQFSF8oQU3uUf5R/qvta8NgFyrQO63KJVOix8=";
    };
  };
  sqlean-x86_64-linux = {
    pname = "sqlean-x86_64-linux";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-linux-x64.zip";
      sha256 = "sha256-vyon1pZ7i+sjrONSq9PkJ7vC2tFHfFNNw8qp0ng0Pdw=";
    };
  };
}
