# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  biome-aarch64-darwin = {
    pname = "biome-aarch64-darwin";
    version = "2.5.10";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.10/biome-darwin-arm64";
      sha256 = "sha256-govCloB2W2VrajVN4B2af59REeavmbBM7+BtCcbS29o=";
    };
  };
  biome-aarch64-linux = {
    pname = "biome-aarch64-linux";
    version = "2.5.10";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.10/biome-linux-arm64-musl";
      sha256 = "sha256-QtTq8UUbd6TFmp2vbgGjRLR8EP04SefcXpijzOYVexc=";
    };
  };
  biome-x86_64-linux = {
    pname = "biome-x86_64-linux";
    version = "2.5.10";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.10/biome-linux-x64-musl";
      sha256 = "sha256-Et5Czs3xx3aKkr4rM3YFOXxIuTXser6UufJY2oeDbfg=";
    };
  };
  design-fontconfig = {
    pname = "design-fontconfig";
    version = "2.18.3";
    src = fetchurl {
      url = "https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/2.18.3/fontconfig-2.18.3.tar.xz";
      sha256 = "sha256-T3tVSjjN94wDP2ZsiHHzdJ4UoJT2Wgf2MMke0LQ9NeM=";
    };
  };
  design-geist-font = {
    pname = "design-geist-font";
    version = "1.7.2";
    src = fetchurl {
      url = "https://github.com/vercel/geist-font/releases/download/v1.7.2/geist-font-v1.7.2.zip";
      sha256 = "sha256-f8gA0qxrkoRIlRluUEGspV2BTBXbcMRPebO4OrgrBOI=";
    };
  };
  design-ghostscript = {
    pname = "design-ghostscript";
    version = "gs10080/ghostscript-10.08.0.tar.xz";
    src = fetchurl {
      url = "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10080/ghostscript-10.08.0.tar.xz";
      sha256 = "sha256-wgSSvI67lsh/ouUqCSbhzajN6V1mFF4BiscT/tXaOM8=";
    };
  };
  design-harfbuzz = {
    pname = "design-harfbuzz";
    version = "14.4.0";
    src = fetchurl {
      url = "https://github.com/harfbuzz/harfbuzz/releases/download/14.4.0/harfbuzz-14.4.0.tar.xz";
      sha256 = "sha256-I1ftlmxs7Xv6cgsGQMAjEGWvARWPvqIVCT/6Fa7UQ3E=";
    };
  };
  design-imagemagick = {
    pname = "design-imagemagick";
    version = "7.1.2-31";
    src = fetchurl {
      url = "https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-31/ImageMagick-7.1.2-31.tar.xz";
      sha256 = "sha256-FoqXELOo1p29IOsKNfFFsMDtNfB2svyY0+tX2qkZw3Y=";
    };
  };
  design-mupdf = {
    pname = "design-mupdf";
    version = "1.28.3";
    src = fetchurl {
      url = "https://mupdf.com/downloads/archive/mupdf-1.28.3-source.tar.gz";
      sha256 = "sha256-N8MgncDgb6TzeB7USDmtkzqeYUPrRzH5ngaSBHFbzvI=";
    };
  };
  design-nodejs_26 = {
    pname = "design-nodejs_26";
    version = "26.8.2";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.8.2/node-v26.8.2.tar.xz";
      sha256 = "sha256-NrN79e5NCSudnf8tGpCxRE+LRT7d9v+Wyr3ruX0y9B0=";
    };
  };
  design-pandoc-aarch64-darwin = {
    pname = "design-pandoc-aarch64-darwin";
    version = "3.11";
    src = fetchurl {
      url = "https://github.com/jgm/pandoc/releases/download/3.11/pandoc-3.11-arm64-macOS.zip";
      sha256 = "sha256-FYBr7flRe/6tcuiP5qZpZjXDaR77tuFSFzRA6cW7ULQ=";
    };
  };
  design-pandoc-aarch64-linux = {
    pname = "design-pandoc-aarch64-linux";
    version = "3.11";
    src = fetchurl {
      url = "https://github.com/jgm/pandoc/releases/download/3.11/pandoc-3.11-linux-arm64.tar.gz";
      sha256 = "sha256-Vu1VZuxB0i7J7gcE5qwLmLoQLpI4Tv1TBhc6ItMUx5o=";
    };
  };
  design-pandoc-x86_64-linux = {
    pname = "design-pandoc-x86_64-linux";
    version = "3.11";
    src = fetchurl {
      url = "https://github.com/jgm/pandoc/releases/download/3.11/pandoc-3.11-linux-amd64.tar.gz";
      sha256 = "sha256-N+2zu89yL5IaAJlBv1h04uDAkmMibJtKLZgHiMsGKrY=";
    };
  };
  design-poppler = {
    pname = "design-poppler";
    version = "26.09.0";
    src = fetchurl {
      url = "https://poppler.freedesktop.org/poppler-26.09.0.tar.xz";
      sha256 = "sha256-gFnq22gFNAdo8TjEZbV/gWTJK0oHc8N+8DHqbA2Yey4=";
    };
  };
  design-poppler-test-data = {
    pname = "design-poppler-test-data";
    version = "48b6219b84fc0a708040cb279d51095cc4e1c603";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/poppler/test.git";
      rev = "48b6219b84fc0a708040cb279d51095cc4e1c603";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-2eH4dZs2J0CeTWrXOYEHb0Xnpfa7tX8mi7AX2E9D41U=";
    };
    date = "2026-08-14";
  };
  design-qpdf = {
    pname = "design-qpdf";
    version = "12.4.1";
    src = fetchurl {
      url = "https://github.com/qpdf/qpdf/releases/download/v12.4.1/qpdf-12.4.1.tar.gz";
      sha256 = "sha256-8EWqJ3viNW/1OomoYilFlYKRF30kg6/CDt58iozThzw=";
    };
  };
  design-temurin-aarch64-darwin = {
    pname = "design-temurin-aarch64-darwin";
    version = "jdk-26.0.2.1+1";
    src = fetchurl {
      url = "https://api.adoptium.net/v3/binary/version/jdk-26.0.2.1+1/mac/aarch64/jre/hotspot/normal/eclipse";
      name = "temurin-jdk-26.0.2.1+1-aarch64-darwin.tar.gz";
      sha256 = "sha256-Y6lLO6BTCAY1NtYMsPm8hHkAowD8U2MMhu6j76eTE6Q=";
    };
  };
  design-temurin-aarch64-linux = {
    pname = "design-temurin-aarch64-linux";
    version = "jdk-26.0.2.1+1";
    src = fetchurl {
      url = "https://api.adoptium.net/v3/binary/version/jdk-26.0.2.1+1/linux/aarch64/jre/hotspot/normal/eclipse";
      name = "temurin-jdk-26.0.2.1+1-aarch64-linux.tar.gz";
      sha256 = "sha256-nhUnaBrkphUETIhDXSwan68f1ce6r5UUpKQgdggVAIc=";
    };
  };
  design-temurin-x86_64-linux = {
    pname = "design-temurin-x86_64-linux";
    version = "jdk-26.0.2.1+1";
    src = fetchurl {
      url = "https://api.adoptium.net/v3/binary/version/jdk-26.0.2.1+1/linux/x64/jre/hotspot/normal/eclipse";
      name = "temurin-jdk-26.0.2.1+1-x86_64-linux.tar.gz";
      sha256 = "sha256-NXcxFoKVVPs45qz5uSs7qLt4VlV8OriF4m59YejI4bA=";
    };
  };
  design-utiluti = {
    pname = "design-utiluti";
    version = "1.5";
    src = fetchurl {
      url = "https://github.com/scriptingosx/utiluti/releases/download/v1.5/utiluti-1.5.pkg";
      sha256 = "sha256-cBhLUejsABesbi3q4jntgmWJAlgpgttXSRLKiIT+Bh8=";
    };
  };
  design-verapdf-cli = {
    pname = "design-verapdf-cli";
    version = "1.31.167";
    src = fetchurl {
      url = "https://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/apps/cli/1.31.167/cli-1.31.167.jar";
      sha256 = "sha256-spyBcL+9XNuJ6UGDfDywq3kgID0Ifw3zK4EkYxcuNTQ=";
    };
  };
  duckdb-aarch64-darwin = {
    pname = "duckdb-aarch64-darwin";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-osx-universal.zip";
      sha256 = "sha256-ekvDqT9/kvW0DNCcIa+vmOQVxsudkXAGSZN4LnefQRU=";
    };
  };
  duckdb-aarch64-linux = {
    pname = "duckdb-aarch64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-arm64.zip";
      sha256 = "sha256-AhYxlwJ6QhSRRzZNMfpnysghCFF6S+QzBKHMIm6u8Ho=";
    };
  };
  duckdb-x86_64-linux = {
    pname = "duckdb-x86_64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-amd64.zip";
      sha256 = "sha256-CMDKEXER/O3hQjnQCTeSNSvv3BdCGMNE0jLBMnlkPQU=";
    };
  };
  sqlean-aarch64-darwin = {
    pname = "sqlean-aarch64-darwin";
    version = "0.28.4";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.4/sqlean-macos-arm64.zip";
      sha256 = "sha256-NlOnDIOnFdcMYnpMtjUjNfmfRox74cm82PQ06Y8IknI=";
    };
  };
  sqlean-aarch64-linux = {
    pname = "sqlean-aarch64-linux";
    version = "0.28.4";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.4/sqlean-linux-arm64.zip";
      sha256 = "sha256-TEOLpVaoUEw+Z5BeBhh2G7KgrPRtHfW/4UAudcAU7M4=";
    };
  };
  sqlean-x86_64-linux = {
    pname = "sqlean-x86_64-linux";
    version = "0.28.4";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.4/sqlean-linux-x64.zip";
      sha256 = "sha256-e+tbjHjiG4cYtXomKK60h7586heIpc7S9vowb3R7RKI=";
    };
  };
}
