# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ast-grep-upstream = {
    pname = "ast-grep-upstream";
    version = "0.45.1";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "ast-grep";
      rev = "0.45.1";
      fetchSubmodules = false;
      sha256 = "sha256-YNn49WuILwe3gyvHSKh3dH5BZKhtR+YeSCCGDu0qulg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-YNn49WuILwe3gyvHSKh3dH5BZKhtR+YeSCCGDu0qulg=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  biome-aarch64-darwin = {
    pname = "biome-aarch64-darwin";
    version = "2.5.7";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.7/biome-darwin-arm64";
      sha256 = "sha256-9x/oCQnS9w8eBRMg9bqd/VU7xe87rO9c3uGwDulqKFw=";
    };
  };
  biome-aarch64-linux = {
    pname = "biome-aarch64-linux";
    version = "2.5.7";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.7/biome-linux-arm64-musl";
      sha256 = "sha256-GfCV2hc/puJ0206rp83P9hveMq02j3VLMYXJ6rzWcgI=";
    };
  };
  biome-x86_64-linux = {
    pname = "biome-x86_64-linux";
    version = "2.5.7";
    src = fetchurl {
      url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.7/biome-linux-x64-musl";
      sha256 = "sha256-RgmkkwaNeoTGHQHV7V7IyvuAW8xSBIa+Y/CjiLvjyCc=";
    };
  };
  duckdb-aarch64-darwin = {
    pname = "duckdb-aarch64-darwin";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-osx-universal.zip";
      sha256 = "sha256-ekvDqT9/kvW0DNCcIa+vmOQVxsudkXAGSZN4LnefQRU=";
    };
  };
  duckdb-aarch64-linux = {
    pname = "duckdb-aarch64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-arm64.zip";
      sha256 = "sha256-AhYxlwJ6QhSRRzZNMfpnysghCFF6S+QzBKHMIm6u8Ho=";
    };
  };
  duckdb-x86_64-linux = {
    pname = "duckdb-x86_64-linux";
    version = "1.5.5";
    src = fetchurl {
      url = "https://github.com/duckdb/duckdb/releases/download/v1.5.5/duckdb_cli-linux-amd64.zip";
      sha256 = "sha256-CMDKEXER/O3hQjnQCTeSNSvv3BdCGMNE0jLBMnlkPQU=";
    };
  };
  nodejs-bin_26-aarch64-darwin = {
    pname = "nodejs-bin_26-aarch64-darwin";
    version = "26.7.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.7.0/node-v26.7.0-darwin-arm64.tar.xz";
      sha256 = "sha256-WV0vk04IG4KWHRpf1BxtvQxalS2ei+W0Vmq3VEJpaNI=";
    };
  };
  nodejs-bin_26-aarch64-linux = {
    pname = "nodejs-bin_26-aarch64-linux";
    version = "26.7.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.7.0/node-v26.7.0-linux-arm64.tar.xz";
      sha256 = "sha256-r8egBAGEhQkqyJhbgXsNVoRHK9lHLgtX0quIc35QCQ0=";
    };
  };
  nodejs-bin_26-x86_64-linux = {
    pname = "nodejs-bin_26-x86_64-linux";
    version = "26.7.0";
    src = fetchurl {
      url = "https://nodejs.org/dist/v26.7.0/node-v26.7.0-linux-x64.tar.xz";
      sha256 = "sha256-mCqiTdi+TIicaoqzN93/OwiWZFsg9COTVugFUsFid+4=";
    };
  };
  pnpm_11 = {
    pname = "pnpm_11";
    version = "11.21.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-11.21.0.tgz";
      sha256 = "sha256-hyN9N+rbedxiagV26zpS0j1wQiwyOuXgD8BckfQyN4A=";
    };
  };
  sqlean-aarch64-darwin = {
    pname = "sqlean-aarch64-darwin";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-macos-arm64.zip";
      sha256 = "sha256-G8qhU4xCuw0qXQhkkJqvV0dbDiuow4BwVXeQsOxaeFo=";
    };
  };
  sqlean-aarch64-linux = {
    pname = "sqlean-aarch64-linux";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-linux-arm64.zip";
      sha256 = "sha256-B02nNIeQFSF8oQU3uUf5R/qvta8NgFyrQO63KJVOix8=";
    };
  };
  sqlean-x86_64-linux = {
    pname = "sqlean-x86_64-linux";
    version = "0.28.3";
    src = fetchTarball {
      url = "https://github.com/nalgeon/sqlean/releases/download/0.28.3/sqlean-linux-x64.zip";
      sha256 = "sha256-vyon1pZ7i+sjrONSq9PkJ7vC2tFHfFNNw8qp0ng0Pdw=";
    };
  };
}
