# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/development/shfmt/config.toml
# ----------------------------------------------------------------------------
# shfmt shell script formatter configuration with style and formatting rules

# --- Core Formatting Settings -----------------------------------------------
# Indentation style (tabs, spaces)
indent_style = "spaces"

# Number of spaces for indentation (when using spaces)
indent_size = 2

# Use tabs for indentation (overrides spaces setting)
use_tabs = false

# Binary operators (&&, ||) formatting
# Options: "before", "after", "same-line"
binary_next_line = "same-line"

# Switch case indentation
# Options: true (indent case statements), false (align with switch)
case_indent = true

# Function opening brace position
# Options: "same-line", "next-line"
function_brace = "same-line"

# --- Language Variant Settings ----------------------------------------------
# Shell language variant
# Options: "bash", "posix", "mksh", "bats"
language = "bash"

# POSIX compliance mode
posix_mode = false

# Keep column alignment in assignments and declarations
keep_column_alignment = true

# --- Whitespace and Spacing -------------------------------------------------
# Simplify code by removing unnecessary elements
simplify = true

# Minify code (remove all optional whitespace)
minify = false

# Space after redirection operators (>, <, >>, etc.)
space_redirects = true

# Keep padding inside parentheses in function definitions
keep_padding = false

# --- Line Length and Wrapping -----------------------------------------------
# Maximum line length (0 = no limit)
max_line_length = 120

# Wrap long lines
wrap_long_lines = true

# Wrap threshold (percentage of max_line_length)
wrap_threshold = 80

# --- Comment Handling -------------------------------------------------------
# Keep comments aligned with code
align_comments = true

# Preserve comment formatting
preserve_comments = true

# Remove empty comment lines
remove_empty_comments = false

# --- Array and List Formatting ----------------------------------------------
# Array element alignment
# Options: "compact", "aligned", "multi-line"
array_format = "compact"

# Keep arrays on single line when possible
single_line_arrays = true

# Maximum array elements per line
max_array_elements = 5

# --- Conditional and Loop Formatting ----------------------------------------
# Format if/then/else statements
# Options: "compact", "expanded"
conditional_format = "compact"

# Keep short conditionals on single line
single_line_conditionals = true

# Format for/while/until loops
# Options: "compact", "expanded"
loop_format = "compact"

# --- Function Formatting ----------------------------------------------------
# Function definition style
# Options: "function", "parentheses", "both"
function_style = "function"

# Keep short functions on single line
single_line_functions = false

# Maximum function length for single line
max_single_line_function = 40

# --- Variable and Parameter Formatting --------------------------------------
# Variable expansion formatting
# Options: "preserve", "normalize", "quote"
variable_expansion = "normalize"

# Quote variable expansions when necessary
quote_variables = true

# Parameter expansion formatting
parameter_expansion = "normalize"

# --- String and Quote Handling ----------------------------------------------
# Quote style preference
# Options: "single", "double", "preserve"
quote_style = "double"

# Escape sequences in strings
# Options: "preserve", "normalize"
escape_sequences = "preserve"

# Remove unnecessary quotes
remove_unnecessary_quotes = true

# --- Command Substitution ---------------------------------------------------
# Command substitution style
# Options: "backticks", "dollar-parens", "preserve"
command_substitution = "dollar-parens"

# Nested command substitution handling
nested_command_substitution = "dollar-parens"

# --- Redirection and Pipes --------------------------------------------------
# Redirection formatting
# Options: "compact", "spaced"
redirection_format = "spaced"

# Pipe formatting
# Options: "same-line", "next-line"
pipe_format = "same-line"

# Here document formatting
heredoc_format = "preserve"

# --- Error Handling and Validation ------------------------------------------
# Check for syntax errors before formatting
check_syntax = true

# Validate shell compatibility
validate_compatibility = true

# Strict mode checking
strict_mode = false

# --- File Processing --------------------------------------------------------
# File extensions to process
file_extensions = [".sh", ".bash", ".zsh", ".ksh", ".dash"]

# Shebang patterns to recognize
shebang_patterns = [
    "#!/bin/sh",
    "#!/bin/bash", 
    "#!/usr/bin/env bash",
    "#!/bin/zsh",
    "#!/usr/bin/env zsh",
    "#!/bin/ksh",
    "#!/bin/dash"
]

# Process files without extensions
process_extensionless = true

# --- Backup and Safety ------------------------------------------------------
# Create backup files before formatting
create_backup = false

# Backup file suffix
backup_suffix = ".bak"

# Dry run mode (show changes without applying)
dry_run = false

# --- Integration Settings ---------------------------------------------------
[integration]
# Editor integration
editor_integration = true

# Git hook integration
git_hook_integration = true

# CI/CD integration
ci_integration = true

# Shell completion
enable_completions = true

# --- Custom Rules -----------------------------------------------------------
[custom_rules]
# Custom formatting rules for specific patterns
# Example: always use double quotes for variables containing spaces
force_double_quotes_with_spaces = true

# Always use $() for command substitution
force_dollar_parens = true

# Prefer [[ ]] over [ ] for conditionals
prefer_double_brackets = true

# Use consistent exit status checking
consistent_exit_status = true

# --- Platform-Specific Settings ---------------------------------------------
# macOS-specific settings
[macos]
# Handle BSD vs GNU differences
bsd_compatibility = true

# Use gshfmt if available
prefer_gnu_tools = false

# Linux-specific settings
[linux]
# GNU tools compatibility
gnu_compatibility = true

# Distribution-specific handling
distro_specific = false

# --- Performance Settings ---------------------------------------------------
[performance]
# Number of worker threads for parallel processing
worker_threads = 0  # 0 = auto-detect

# Buffer size for file operations
buffer_size = 8192

# Memory limit for large files (MB)
memory_limit = 100

# --- Logging and Debugging --------------------------------------------------
[logging]
# Log level (error, warn, info, debug, trace)
log_level = "info"

# Log file location
log_file = ""

# Enable verbose output
verbose = false

# Debug mode
debug = false

# --- Output Settings --------------------------------------------------------
[output]
# Output format (formatted, diff, json)
format = "formatted"

# Show diff when formatting
show_diff = false

# Diff context lines
diff_context = 3

# Color output
colored_output = true

# --- Quality Checks ---------------------------------------------------------
[quality]
# Check for common shell scripting issues
check_common_issues = true

# Warn about deprecated constructs
warn_deprecated = true

# Check for security issues
security_checks = false

# Performance optimization suggestions
performance_suggestions = false

# --- Exclusion Patterns ----------------------------------------------------
[exclusions]
# Files to exclude from formatting
exclude_files = [
    "*.min.sh",
    "*.generated.sh",
    "vendor/*",
    "third_party/*"
]

# Directories to exclude
exclude_directories = [
    ".git",
    "node_modules",
    "vendor",
    "third_party"
]

# Patterns to exclude (glob patterns)
exclude_patterns = [
    "*.template.sh",
    "*.example.sh"
]