# Title         : db-tools.nix
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/languages/db-tools.nix
# ----------------------------------------------------------------------------
# Database and SQL tooling: clients, linters, analytics, and the terminal front doors (Harlequin IDE, sq source catalog, VisiData tabular workbench).
{
  config,
  pkgs,
  lib,
  ...
}: let
  tomlFormat = pkgs.formats.toml {};
  style = import ../../../style.nix;
  sqlDialects = ["postgres" "duckdb" "sqlite"];

  # PostgreSQL 18 client roster; server extensions stay Docker-owned by forge-provision.
  postgres18ForgeTools = pkgs.runCommand "postgres18-forge-client-tools" {nativeBuildInputs = [pkgs.makeWrapper];} ''
    mkdir -p "$out/bin"
    for bin in psql pg_dump pg_dumpall pg_restore pg_isready pgbench pg_amcheck createdb dropdb createuser dropuser vacuumdb reindexdb clusterdb; do
      makeWrapper "${pkgs.postgresql_18}/bin/$bin" "$out/bin/$bin"
    done
  '';

  # Harlequin themes are named Textual themes only; dracula matches the estate palette variant. One profile per local engine, DuckDB is the front door.
  harlequinProfile = adapter: {
    inherit adapter;
    theme = "dracula";
    limit = 500;
  };
  harlequinConfig = {
    default_profile = "duckdb";
    profiles = lib.genAttrs ["duckdb" "sqlite" "postgres"] harlequinProfile;
  };

  # sqruff discovery is cwd-only with no user-level lookup; the wrapper injects a house config solely when the working directory carries no
  # project config and the caller passes none, so project law always wins. Dialect is a filename fact (estate law): the first .sql argument's
  # basename picks the house dialect, and fmt keeps its batches dialect-homogeneous.
  sqruff = pkgs.writeShellApplication {
    name = "sqruff";
    text = ''
      [[ -f "$PWD/.sqruff" || -f "$PWD/.sqlfluff" ]] && exec ${pkgs.sqruff}/bin/sqruff "$@"
      dialect=""
      for arg in "$@"; do
        case "$arg" in
          --config | --config=*) exec ${pkgs.sqruff}/bin/sqruff "$@" ;;
          *.sql | *.SQL)
            if [[ -z "$dialect" ]]; then
              base="''${arg##*/}"
              case "''${base,,}" in
                duckdb-*) dialect=duckdb ;;
                sqlite-*) dialect=sqlite ;;
                *) dialect=postgres ;;
              esac
            fi
            ;;
        esac
      done
      exec ${pkgs.sqruff}/bin/sqruff --config "${config.xdg.configHome}/sqruff/''${dialect:-postgres}.cfg" "$@"
    '';
  };
in {
  home.packages = with pkgs; [
    sqlite-interactive # Enhanced sqlite3 shell with line editing and metadata helpers
    sqlite-vec # Vector similarity extension for SQLite
    sqlite-utils # Python-based CLI for SQLite database management
    libspatialite # Spatial SQL extension for geospatial work
    sqlfluff # SQL linter and formatter supporting multiple dialects
    duckdb # In-memory analytics database with SQL interface
    postgres18ForgeTools # PostgreSQL 18 client commands; server extensions are Docker-owned by forge-provision
    pgroll # Online PostgreSQL schema migration CLI
    pgloader # Data loading/migration into PostgreSQL
    pgbadger # PostgreSQL log analyzer
    parquet-tools # Parquet file inspector
    minio-client # S3-compatible object storage CLI (mc)
    s5cmd # Fast S3/object-store batch CLI
    usql # Universal SQL CLI for cross-database interactive sessions
    pgcli # Interactive PostgreSQL shell with completion
    litecli # Interactive SQLite shell with completion
    sqruff # SQL linter/formatter (let-bound house-config fallback wrapper)
    pgformatter # PostgreSQL SQL formatter
    pg_activity # PostgreSQL activity monitor
    pgmetrics # PostgreSQL metric collection CLI
    sqlean # Extension library bundle (regexp, uuid, stats, etc.)
    postgres-language-server # Postgres LSP; includes postgres-language-server and postgrestools
    sqlite-forge # Explicit SQLite shell with SQLean, sqlite-vec, and SpatiaLite loaded
    (harlequin.override {withBigQueryAdapter = false;}) # Terminal SQL IDE with duckdb/sqlite/postgres adapters; config below
    sq # Cross-source catalog/query bridge; sq.yml is a self-mutating source catalog (user state), credentials stay in keyring/env
    visidata # Interactive tabular workbench for CSV/parquet/JSON/directory sheets; config below
  ];

  xdg.configFile =
    {
      # HARLEQUIN_CONFIG_PATH (environments/languages.nix) pins discovery to this file; the postgres profile rides libpq PG* environment defaults.
      "harlequin/config.toml".source = tomlFormat.generate "harlequin-config" harlequinConfig;

      # VisiData colors are curses-palette only; the default dark theme stands. VD_CONFIG/VD_DIR (environments/languages.nix) own discovery and
      # state paths — the vendored appdirs would otherwise resolve to ~/Library/Preferences on darwin.
      "visidata/config.py".text = ''
        # Generated by Home Manager (Parametric Forge).
        options.motd_url = ""  # no startup network fetch
      '';

      # SQL house style projected from the style vocabulary (postgres default dialect). Fallback order per tool: sqruff rides the wrapper above,
      # one config per dialect; pg_format auto-reads ./.pg_format before this rc; sqlfluff resolves user-level config behind every
      # project/pyproject location, so project law always wins.
      "pg_format/pg_format.conf".text = ''
        spaces=${toString style.indent}
        wrap-limit=${toString style.width}
      '';
      "sqlfluff".text = style.sql "sqlfluff" "postgres";
    }
    // lib.listToAttrs (map (d: {
        name = "sqruff/${d}.cfg";
        value.text = style.sql "sqruff" d;
      })
      sqlDialects);

  home.file.".sqliterc".text = lib.concatStringsSep "\n" [
    "-- Auto-generated by Home Manager (Parametric Forge)"
    "-- Harmless interactive defaults only; use sqlite-forge for native extensions."
    ""
    ".mode column"
    ".headers on"
    ".nullvalue NULL"
  ];
}
