# Title         : db-tools.nix
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/languages/db-tools.nix
# ----------------------------------------------------------------------------
# Database and SQL tooling for interactive queries, linting, and analytics.
{
  pkgs,
  lib,
  ...
}: let
  postgres18ForgeTools = pkgs.runCommand "postgres18-forge-client-tools" {nativeBuildInputs = [pkgs.makeWrapper];} ''
    runHook preInstall
    mkdir -p "$out/bin"
    for bin in psql pg_dump pg_restore pg_isready pgbench pg_amcheck createdb dropdb createuser dropuser vacuumdb reindexdb clusterdb; do
      makeWrapper "${pkgs.postgresql_18}/bin/$bin" "$out/bin/$bin"
    done
    runHook postInstall
  '';
in {
  home.packages = with pkgs; [
    sqlite-interactive # Enhanced sqlite3 shell with line editing and metadata helpers
    sqlite-vec # Vector similarity extension for SQLite
    sqlite-utils # Python-based CLI for SQLite database management
    libspatialite # Spatial SQL extension for geospatial work
    sqlfluff # SQL linter and formatter supporting multiple dialects
    duckdb # In-memory analytics database with SQL interface
    postgres18ForgeTools # PostgreSQL 18 client commands; server extensions are Docker-owned by forge-provision
    atlas # Declarative schema diff/migration CLI
    pgroll # Online PostgreSQL schema migration CLI
    pgloader # Data loading/migration into PostgreSQL
    pgbadger # PostgreSQL log analyzer
    parquet-tools # Parquet file inspector
    minio-client # S3-compatible object storage CLI (mc)
    s5cmd # Fast S3/object-store batch CLI
    usql # Universal SQL CLI for cross-database interactive sessions
    pgcli # Interactive PostgreSQL shell with completion
    litecli # Interactive SQLite shell with completion
    sqruff # Fast SQL linter/formatter for DuckDB-style SQL workflows
    pgformatter # PostgreSQL SQL formatter
    pg_activity # PostgreSQL activity monitor
    pgmetrics # PostgreSQL metric collection CLI
    sqlean # Extension library bundle (regexp, uuid, stats, etc.)
    postgres-language-server # Postgres LSP; includes postgres-language-server and postgrestools
    sqlite-forge # Explicit SQLite shell with SQLean, sqlite-vec, and SpatiaLite loaded
  ];

  home.file.".sqliterc".text = lib.concatStringsSep "\n" [
    "-- Auto-generated by Home Manager (Parametric Forge)"
    "-- Harmless interactive defaults only; use sqlite-forge for native extensions."
    ""
    ".mode column"
    ".headers on"
    ".nullvalue NULL"
  ];
}
