# Title         : bottom.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/system/bottom/bottom.toml
# ----------------------------------------------------------------------------
# Bottom system monitor configuration with optimized layouts and themes

# --- Core Settings ------------------------------------------------------------
# Color scheme (auto, light, dark, or custom theme name)
color = "dark"

# Default time interval for updates (in milliseconds)
default_time_value = 1000

# Time delta for process CPU usage calculation (in milliseconds)
time_delta = 1000

# Hide time in graphs
hide_time = false

# Use old network legend style
use_old_network_legend = false

# Hide average CPU usage
hide_avg_cpu = false

# Use dot markers in graphs instead of braille
dot_marker = false

# Left legend for graphs
left_legend = false

# Show current usage in legends
current_usage = true

# Group processes by default
group_processes = false

# Case sensitive process search
case_sensitive = false

# Whole word process search
whole_word = false

# Use regex for process search
regex = false

# --- Display Settings --------------------------------------------------------
# Default widget type on startup (cpu, mem, net, proc, temp, disk)
default_widget_type = "proc"

# Default widget count (for widgets that support it)
default_widget_count = 1

# Disable mouse support
disable_click = false

# Show table headers
no_write = false

# Temperature type (celsius, fahrenheit, kelvin)
temperature_type = "celsius"

# Rate type for network (bit, byte)
rate = "byte"

# --- Process Settings --------------------------------------------------------
# Show process command instead of name
show_process_command = false

# Tree mode for processes
tree = false

# Show process threads
show_table_scroll_position = true

# Process sorting (pid, name, cpu, mem, read, write, time)
process_command = false

# --- Memory Settings ---------------------------------------------------------
# Memory legend (none, top-left, top, top-right, left, right, bottom-left, bottom, bottom-right)
memory_legend = "top-left"

# Show swap memory
show_swap = true

# Show cache and buffer memory
show_cache_info = true

# --- Network Settings --------------------------------------------------------
# Network legend position
network_legend = "top-left"

# Use binary prefixes for network (1024 vs 1000)
network_use_binary_prefix = false

# Use bytes instead of bits for network
network_use_bytes = true

# --- Disk Settings -----------------------------------------------------------
# Disk legend position  
disk_legend = "top-left"

# Use binary prefixes for disk (1024 vs 1000)
disk_use_binary_prefix = true

# --- Temperature Settings ---------------------------------------------------
# Temperature legend position
temp_legend = "top-left"

# --- CPU Settings ------------------------------------------------------------
# CPU legend position
cpu_legend = "top-left"

# Show average CPU line
avg_cpu = true

# CPU left legend
cpu_left_legend = false

# --- Battery Settings -------------------------------------------------------
# Battery legend position (if battery widget is used)
battery_legend = "top-left"

# --- Layout Configuration ---------------------------------------------------
# Custom layout using RON (Rusty Object Notation) format
# This defines the arrangement of widgets on screen

[[row]]
    ratio = 30
    [[row.child]]
    type = "cpu"
    ratio = 4
    [[row.child]]
    type = "mem"
    ratio = 3
    [[row.child]]
    type = "temp"
    ratio = 4

[[row]]
    ratio = 40
    [[row.child]]
    type = "net"
    ratio = 4
    [[row.child]]
    type = "proc"
    ratio = 6

[[row]]
    ratio = 30
    [[row.child]]
    type = "disk"

# --- Color Theme Configuration -----------------------------------------------
# Custom color theme (when color = "custom")
[colors]
# Widget colors
table_header_color = "LightBlue"
all_entry_color = "White"
avg_entry_color = "Red"
cpu_core_colors = ["LightMagenta", "LightYellow", "LightCyan", "LightGreen", "LightBlue", "LightRed"]

# RAM and swap colors
ram_color = "LightMagenta"
swap_color = "LightYellow"
cache_color = "LightCyan"

# RX and TX colors
rx_color = "LightBlue"
tx_color = "LightRed"

# Widget title color
widget_title_color = "Gray"

# Border color
border_color = "Gray"

# Highlighted border color
highlighted_border_color = "LightBlue"

# Text colors
text_color = "Gray"
selected_text_color = "Black"
selected_bg_color = "LightBlue"

# Graph colors
graph_color = "Gray"
high_battery_color = "Green"
medium_battery_color = "Yellow"
low_battery_color = "Red"

# --- Keybindings -------------------------------------------------------------
# Custom keybindings (optional - defaults are usually sufficient)
[keybindings]
# Process management
kill = "k"
# Navigation
up = "k"
down = "j"
left = "h"
right = "l"
# Sorting
sort_cpu = "c"
sort_mem = "m"
sort_pid = "p"
sort_name = "n"
sort_time = "t"
sort_read = "r"
sort_write = "w"
# Search
search = "/"
next_search = "n"
prev_search = "N"
# View toggles
tree = "T"
sort_reverse = "R"
group_processes = "g"
# Zoom
zoom_in = "+"
zoom_out = "-"
reset_zoom = "="
# Quit
quit = "q"

# --- Advanced Settings ------------------------------------------------------
# Enable GPU monitoring (if supported)
enable_gpu_memory = true

# Enable cache and buffer info
enable_cache_memory = true

# Show process start time
show_process_start_time = false

# Retention period for data (in seconds)
retention = 600

# --- Platform-Specific Settings ---------------------------------------------
# macOS-specific settings
[macos]
# Show temperature sensors
show_temperature = true
# Show battery information
show_battery = true

# Linux-specific settings
[linux]
# Show temperature sensors
show_temperature = true
# Show battery information  
show_battery = true
# Use sensors command for temperature
use_sensors = true