# Title         : 01.home/activation.nix
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/activation.nix
# ----------------------------------------------------------------------------
# Home activation scripts for 1Password secrets and XDG template generation.

{
  config,
  lib,
  myLib,
  context,
  pkgs,
  ...
}:

{
  # --- Home Activation Scripts ----------------------------------------------
  home.activation = {
    # --- Yazi Plugin Installation --------------------------------------------
    yaziPlugins = lib.hm.dag.entryAfter [ "installPackages" ] ''
      # Ensure full system PATH is available + nix user packages
      export PATH="$HOME/.nix-profile/bin:/run/current-system/sw/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

      # Auto-install/update Yazi plugins when package.toml changes
      YAZI_CONFIG="${config.xdg.configHome}/yazi/package.toml"
      YAZI_CACHE="${config.xdg.cacheHome}/yazi/plugins.sha256"

      # Check if yazi is available
      if command -v ya >/dev/null 2>&1; then
        # Calculate current package.toml checksum
        CURRENT_HASH=$(shasum -a 256 "$YAZI_CONFIG" | cut -d' ' -f1)
        CACHED_HASH=$(cat "$YAZI_CACHE" 2>/dev/null || echo "")

        # Install/update plugins only if package.toml changed
        if [ "$CURRENT_HASH" != "$CACHED_HASH" ]; then
          echo "[Yazi] Synchronizing plugins..."

          # Install/update all plugins from package.toml with detailed error output
          if ya pack -i 2>&1; then
            echo "    [OK] Yazi plugins updated"
            echo "$CURRENT_HASH" > "$YAZI_CACHE"
          else
            echo "    [WARN] Some plugins failed to install (see output above for details)"
          fi
        else
          echo "[Yazi] Plugins up to date (config unchanged)"
        fi
      else
        echo "[Yazi] Plugin manager 'ya' not found in PATH, skipping plugin installation"
      fi
    '';

    # --- SQLite Extensions Setup --------------------------------------------
    sqliteExtensions = lib.hm.dag.entryAfter [ "createXdgDirs" ] ''
      # Install sqlean (not in nixpkgs)
      if [ ! -f "$HOME/.local/lib/sqlean/uuid.dylib" ]; then
        echo "[SQLite] Installing sqlean extensions..."
        ${lib.optionalString context.isDarwin ''
          ARCH=$([ "$(uname -m)" = "arm64" ] && echo "aarch64" || echo "x86_64")
          curl -sL "https://github.com/nalgeon/sqlean/releases/latest/download/sqlean-macos-$ARCH.zip" \
            | tar -xz -C "$HOME/.local/lib/sqlean" --strip-components=0 2>/dev/null || echo "  [WARN] Manual install required"
        ''}
      fi
      # Link sqlite-vec (from nixpkgs)
      mkdir -p "$HOME/.local/lib/sqlite-vec"
      if [ -f "${pkgs.sqlite-vec}/lib/vec0.dylib" ]; then
        ln -sf "${pkgs.sqlite-vec}/lib/vec0.dylib" "$HOME/.local/lib/sqlite-vec/vec0.dylib"
        echo "    [OK] sqlite-vec linked from Nix store"
      elif [ -f "${pkgs.sqlite-vec}/lib/sqlite-vec.dylib" ]; then
        ln -sf "${pkgs.sqlite-vec}/lib/sqlite-vec.dylib" "$HOME/.local/lib/sqlite-vec/vec0.dylib"
        echo "    [OK] sqlite-vec linked from Nix store (alternative name)"
      else
        echo "    [WARN] sqlite-vec not found in expected locations"
      fi
      # Link libspatialite
      ln -sf "${pkgs.libspatialite}/lib/mod_spatialite.dylib" "$HOME/.local/lib/mod_spatialite.dylib" 2>/dev/null || true
    '';

    # --- Basic 1Password Directory Setup -----------------------------------
    opDirectories = lib.hm.dag.entryAfter [ "sqliteExtensions" ] ''
      echo "[1Password] Setting up directories and permissions..."

      # Ensure SSH directory exists with proper permissions
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh

      # Ensure 1Password config directory exists
      mkdir -p ~/.config/op

      echo "  [OK] Basic 1Password directories created"
    '';

  };
  # --- XDG Config Files -----------------------------------------------------
  xdg.configFile."op/env.template" = {
    text = ''
      # 1Password Secret References Template
      # Generated by Parametric Forge
      # Use with: op run --env-file=~/.config/op/env.template -- <command>

      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: ref: "${name}=${ref}") config.secrets.environment)}
    '';
    onChange = ''
      echo "[Parametric Forge] Updated 1Password environment template"
      echo "  Location: ${config.secrets.paths.template}"
      echo "  Secrets configured: ${toString (builtins.length (builtins.attrNames config.secrets.environment))}"
    '';
  };

}
