# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/system/procs/config.toml
# ----------------------------------------------------------------------------
# Process viewer configuration with Dracula theme

# --- Column Definitions ---------------------------------------------------
[[columns]]
kind = "Pid"
style = "BrightYellow|Yellow"
numeric_search = true
align = "Left"
max_width = 8

[[columns]]
kind = "User"
style = "BrightGreen|Green"
nonnumeric_search = true
align = "Left"
min_width = 8

[[columns]]
kind = "CpuTime"
style = "BrightCyan|Cyan"
align = "Right"

[[columns]]
kind = "UsageCpu"
style = "BrightMagenta|Magenta"
numeric_search = true
align = "Right"

[[columns]]
kind = "UsageMem"
style = "BrightBlue|Blue"
numeric_search = true
align = "Right"

[[columns]]
kind = "State"
style = "BrightWhite|White"
align = "Center"

[[columns]]
kind = "Command"
style = "BrightWhite|White"
nonnumeric_search = true
max_width = 60
min_width = 20

# --- Style Configuration (Dracula Theme) ---------------------------------
[style]
header = "BrightWhite|Black"  # Dracula foreground for headers
unit = "Blue|Black"            # Dracula comment for units
tree = "Cyan|Black"            # Dracula cyan for tree lines

# CPU usage percentage colors (gradient from green to red)
[style.by_percentage]
color_000 = "BrightGreen|Green"   # 0% - Green (#50fa7b)
color_025 = "Green|Green"         # 25% - Darker green
color_050 = "BrightYellow|Yellow" # 50% - Yellow (#f1fa8c)
color_075 = "Yellow|Yellow"       # 75% - Orange (#ffb86c)
color_100 = "BrightRed|Red"       # 100% - Red (#ff5555)

# Process state colors
[style.by_state]
color_d = "Blue|Blue"          # Uninterruptible sleep (disk) - Comment
color_r = "BrightGreen|Green"  # Running - Green
color_s = "BrightCyan|Cyan"    # Sleeping - Cyan
color_t = "BrightYellow|Yellow" # Stopped - Yellow
color_z = "BrightRed|Red"      # Zombie - Red
color_i = "Magenta|Magenta"    # Idle - Purple
color_l = "BrightMagenta|Magenta" # Lock - Bright Purple
color_w = "BrightBlue|Blue"    # Paging - Bright Blue

# --- Search Configuration ------------------------------------------------
[search]
numeric_search = "Exact"      # Exact match for PIDs and numbers
nonnumeric_search = "Partial" # Partial match for text (commands, users)
logic = "And"                 # All search terms must match
case = "Smart"                # Case-insensitive unless uppercase used

# --- Display Configuration -----------------------------------------------
[display]
show_self = false            # Don't show procs process itself
show_thread = false          # Don't show threads by default
cut_to_terminal = true       # Truncate to terminal width
theme = "Auto"               # Auto-detect terminal background
color_mode = "Auto"          # Auto-detect color support
show_header = true           # Display column headers
show_kthreads = false        # Hide kernel threads by default

# --- Sort Configuration --------------------------------------------------
[sort]
column = 3                   # Sort by CPU by default (0-indexed)
order = "Descending"         # High CPU usage first

# --- Pager Configuration -------------------------------------------------
[pager]
mode = "Auto"                # Use pager for long output
detect_width = true          # Detect pager width
use_builtin = false          # Use external pager
command = "less -SR"         # Pager command

# --- Docker Configuration (optional) ------------------------------------
# Enable if using Docker/Colima
[docker]
path = "unix:///var/run/docker.sock"  # Standard Docker socket path