[toolchain]
channel = "1.89.0"
components = ["rustfmt", "clippy", "rust-analyzer", "rust-src"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
