# Title         : rustfmt.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge Interface
# License       : MIT
# Path          : interface/rustfmt.toml
# ----------------------------------------------------------------------------
# Rust formatter configuration with project standards

# --- Edition Configuration -----------------------------------------------
edition = "2021"

# --- Project Standards ---------------------------------------------------
max_width = 120
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# --- Import Organization (stable features only) -------------------------
reorder_imports = true
reorder_modules = true
