# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/network/xh/config.toml
# ----------------------------------------------------------------------------
# xh HTTP client configuration with themes and request optimization

# --- Core Settings ------------------------------------------------------------
# Default HTTP method when not specified
default_method = "GET"

# Default request timeout in seconds
timeout = 30

# Connection timeout in seconds
connect_timeout = 10

# Follow redirects automatically
follow_redirects = true

# Maximum number of redirects to follow
max_redirects = 10

# Verify SSL certificates
verify_ssl = true

# --- Output Settings ---------------------------------------------------------
# Default output format (auto, json, headers, body, verbose)
output_format = "auto"

# Pretty print JSON responses
pretty_print = true

# Use colored output
colored_output = true

# Color theme (auto, dark, light, none)
color_theme = "dark"

# Show response headers
show_headers = true

# Show request headers
show_request_headers = false

# Show response metadata (status, timing, etc.)
show_metadata = true

# --- Request Settings --------------------------------------------------------
# Default User-Agent string
user_agent = "xh/1.0 (Parametric Forge)"

# Default Accept header
default_accept = "application/json, */*"

# Default Content-Type for POST/PUT requests
default_content_type = "application/json"

# Automatically detect JSON content
auto_json = true

# --- Authentication ---------------------------------------------------------
# Default authentication method (basic, bearer, digest)
default_auth_method = "bearer"

# Store authentication tokens (be careful with sensitive data)
store_auth = false

# Authentication cache duration in seconds
auth_cache_duration = 3600

# --- Session Management -----------------------------------------------------
# Enable session support
enable_sessions = true

# Session storage directory
session_dir = "$XDG_DATA_HOME/xh/sessions"

# Default session name
default_session = "default"

# Session timeout in seconds
session_timeout = 86400

# --- Proxy Settings ----------------------------------------------------------
# HTTP proxy URL (format: http://host:port)
http_proxy = ""

# HTTPS proxy URL (format: https://host:port)
https_proxy = ""

# No proxy hosts (comma-separated list)
no_proxy = "localhost,127.0.0.1,::1"

# --- Performance Settings ---------------------------------------------------
# Connection pool size
connection_pool_size = 10

# Keep-alive timeout in seconds
keep_alive_timeout = 60

# Enable HTTP/2
enable_http2 = true

# Enable compression
enable_compression = true

# Buffer size for streaming responses
stream_buffer_size = 8192

# --- Logging and Debugging --------------------------------------------------
# Log level (error, warn, info, debug, trace)
log_level = "info"

# Log file location (empty = no file logging)
log_file = ""

# Enable request/response logging
log_requests = false
log_responses = false

# Log body content (be careful with sensitive data)
log_body = false

# --- Custom Headers ----------------------------------------------------------
# Default headers to include with every request
[default_headers]
"Accept-Encoding" = "gzip, deflate, br"
"Cache-Control" = "no-cache"
"Connection" = "keep-alive"

# --- Color Theme Configuration -----------------------------------------------
[themes.dark]
# HTTP method colors
method_get = "green"
method_post = "yellow"
method_put = "blue"
method_patch = "magenta"
method_delete = "red"
method_head = "cyan"
method_options = "white"

# Status code colors
status_1xx = "cyan"          # Informational
status_2xx = "green"         # Success
status_3xx = "yellow"        # Redirection
status_4xx = "red"           # Client Error
status_5xx = "bright_red"    # Server Error

# Header colors
header_name = "cyan"
header_value = "white"
header_separator = "gray"

# Body content colors
json_key = "blue"
json_string = "green"
json_number = "magenta"
json_boolean = "yellow"
json_null = "red"

# URL and path colors
url_scheme = "blue"
url_host = "green"
url_path = "white"
url_query = "yellow"
url_fragment = "magenta"

# Timing and metadata colors
timing = "gray"
metadata = "cyan"

[themes.light]
# Light theme colors (for bright terminals)
method_get = "dark_green"
method_post = "dark_yellow"
method_put = "dark_blue"
method_patch = "dark_magenta"
method_delete = "dark_red"
method_head = "dark_cyan"
method_options = "black"

status_1xx = "dark_cyan"
status_2xx = "dark_green"
status_3xx = "dark_yellow"
status_4xx = "dark_red"
status_5xx = "red"

header_name = "dark_cyan"
header_value = "black"
header_separator = "gray"

json_key = "dark_blue"
json_string = "dark_green"
json_number = "dark_magenta"
json_boolean = "dark_yellow"
json_null = "dark_red"

url_scheme = "dark_blue"
url_host = "dark_green"
url_path = "black"
url_query = "dark_yellow"
url_fragment = "dark_magenta"

timing = "gray"
metadata = "dark_cyan"

# --- Request Profiles --------------------------------------------------------
# Predefined request configurations for common scenarios
[profiles.api]
default_headers = { "Content-Type" = "application/json", "Accept" = "application/json" }
timeout = 60
follow_redirects = true
verify_ssl = true

[profiles.web]
default_headers = { "Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" }
user_agent = "Mozilla/5.0 (compatible; xh/1.0)"
timeout = 30
follow_redirects = true

[profiles.debug]
show_request_headers = true
show_headers = true
show_metadata = true
log_requests = true
log_responses = true
output_format = "verbose"

[profiles.fast]
timeout = 5
connect_timeout = 2
follow_redirects = false
show_headers = false
show_metadata = false

# --- Custom Commands ---------------------------------------------------------
# Aliases for common request patterns
[aliases]
get = ["GET"]
post = ["POST", "--json"]
put = ["PUT", "--json"]
patch = ["PATCH", "--json"]
delete = ["DELETE"]
head = ["HEAD"]
options = ["OPTIONS"]

# --- Integration Settings ---------------------------------------------------
[integration]
# Shell completion support
enable_completions = true

# Editor for request body editing
editor = "$EDITOR"

# Pager for long responses
pager = "$PAGER"

# External tools integration
[integration.tools]
# JSON formatter
json_formatter = "jq"

# XML formatter  
xml_formatter = "xmllint --format"

# HTML formatter
html_formatter = "tidy -i -q"

# --- Security Settings ------------------------------------------------------
[security]
# Certificate bundle location
ca_bundle = ""

# Client certificate file
client_cert = ""

# Client private key file
client_key = ""

# Disable SSL verification for specific hosts
insecure_hosts = []

# Maximum response size in bytes (0 = unlimited)
max_response_size = 0

# --- Advanced Settings ------------------------------------------------------
[advanced]
# Custom DNS resolver
dns_resolver = ""

# Local address to bind to
local_address = ""

# TCP keep-alive settings
tcp_keepalive = true
tcp_keepalive_idle = 60
tcp_keepalive_interval = 30
tcp_keepalive_count = 3

# Socket options
socket_options = {}

# --- Environment Integration ------------------------------------------------
[environment]
# Environment variables to use for configuration
proxy_from_env = true
auth_from_env = true
headers_from_env = true

# Environment variable prefixes
env_prefix = "XH_"
proxy_env_vars = ["HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY"]