# Title         : keymap.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/keymap.toml
# ----------------------------------------------------------------------------
# Custom keybindings for Yazi file manager

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # --- System Integration ---------------------------------------------------
  { on = "<C-p>", run = 'shell -- qlmanage -p "$@"', desc = "macOS Quick Look" },

  # --- Standard Keybinding Overrides ----------------------------------------
  { on = "<C-y>", run = "plugin augment-command -- quit", desc = "Quit Yazi" },

  # --- Custom Shell Keybindings ---------------------------------------------
  { on = "<C-A-D-y>", run = "shell 'yazi-focus-nvim.sh'", desc = "Focus nvim pane" },
  { on = "<C-A-D-p>", run = "shell 'yazi-open-dir.sh \"$0\"'", desc = "Open directory in new pane" },
  { on = "<C-A-D-r>", run = "shell 'yazi-reveal.sh \"$1\"'", desc = "Reveal file in sidebar" },

  # --- Plugin Keybindings ---------------------------------------------------
  { on = "F", run = "plugin easyjump", desc = "Jump to file/directory with fuzzy search" },

  # Toggle Pane Plugin
  { on = "[", run = "plugin toggle-pane min-parent", desc = "Toggle parent pane (left)" },
  { on = "]", run = "plugin toggle-pane min-preview", desc = "Toggle preview pane (right)" },
  { on = "\\", run = "plugin toggle-pane max-current", desc = "Maximize/restore current pane (middle)" },

  # Augment Command Plugin
  { on = "q", run = "plugin augment-command -- quit", desc = "Quit the process" },
  { on = "Q", run = "plugin augment-command -- quit --no-cwd-file", desc = "Quit without outputting cwd-file" },
  { on = "l", run = "plugin augment-command -- enter", desc = "Enter the child directory" },
  { on = "<Right>", run = "plugin augment-command -- enter", desc = "Enter the child directory" },
  { on = "h", run = "plugin augment-command -- leave", desc = "Back to the parent directory" },
  { on = "<Left>", run = "plugin augment-command -- leave", desc = "Back to the parent directory" },
  { on = "<Enter>", run = "plugin augment-command -- open", desc = "Open selected files" },
  { on = "o", run = "plugin augment-command -- open", desc = "Open selected files" },
  { on = "O", run = "plugin augment-command -- open --interactive", desc = "Open selected files interactively" },
  { on = "j", run = "plugin augment-command -- arrow 1", desc = "Next file" },
  { on = "k", run = "plugin augment-command -- arrow -1", desc = "Previous file" },
  { on = "<Down>", run = "plugin augment-command -- arrow 1", desc = "Next file" },
  { on = "<Up>", run = "plugin augment-command -- arrow -1", desc = "Previous file" },
  { on = ['g', 'g'], run = "plugin augment-command -- arrow top", desc = "Go to top" },
  { on = "G", run = "plugin augment-command -- arrow bot", desc = "Go to bottom" },
  { on = "p", run = "plugin augment-command -- paste", desc = "Paste yanked files" },
  { on = "P", run = "plugin augment-command -- paste --force", desc = "Paste yanked files (overwrite if the destination exists)" },
  { on = "d", run = "plugin augment-command -- remove", desc = "Trash selected files" },
  { on = "D", run = "plugin augment-command -- remove --permanently", desc = "Permanently delete selected files" },
  { on = "r", run = "plugin augment-command -- rename --cursor=before_ext", desc = "Rename selected file(s)" },
  { on = "a", run = "plugin augment-command -- create", desc = "Create a file (ends with / for directories)" },
  { on = ";", run = "plugin augment-command -- shell --interactive", desc = "Run a shell command" },
  { on = ":", run = "plugin augment-command -- shell --block --interactive", desc = "Run a shell command (block until finishes)" },
  { on = "t", run = "plugin augment-command -- tab_create --current", desc = "Create a new tab with CWD" },
  { on = "1", run = "plugin augment-command -- tab_switch 0", desc = "Switch to first tab" },
  { on = "2", run = "plugin augment-command -- tab_switch 1", desc = "Switch to second tab" },
  { on = "3", run = "plugin augment-command -- tab_switch 2", desc = "Switch to third tab" },
  { on = "4", run = "plugin augment-command -- tab_switch 3", desc = "Switch to fourth tab" },
  { on = "5", run = "plugin augment-command -- tab_switch 4", desc = "Switch to fifth tab" },
  { on = "6", run = "plugin augment-command -- tab_switch 5", desc = "Switch to sixth tab" },
  { on = "7", run = "plugin augment-command -- tab_switch 6", desc = "Switch to seventh tab" },
  { on = "8", run = "plugin augment-command -- tab_switch 7", desc = "Switch to eighth tab" },
  { on = "9", run = "plugin augment-command -- tab_switch 8", desc = "Switch to ninth tab" },
]
