# Title         : keymap.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/keymap.toml
# ----------------------------------------------------------------------------
# Custom keybindings for Yazi file manager

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # --- System Integration ---------------------------------------------------
  { on = "<C-p>", run = 'shell -- qlmanage -p "$@"', desc = "macOS Quick Look" },

  # --- Custom Shell Keybindings ---------------------------------------------
  { on = "<C-A-D-y>", run = "shell 'yazi-focus-nvim.sh'", desc = "Focus nvim pane" },
  { on = "<C-A-D-p>", run = "shell 'yazi-open-dir.sh \"$0\"'", desc = "Open directory in new pane" },
  { on = "<C-A-D-r>", run = "shell 'yazi-reveal.sh \"$1\"'", desc = "Reveal file in sidebar" },

  # --- Plugin Keybindings ---------------------------------------------------
  { on = "E", run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },

  # --- Standard Keybinding Overrides ----------------------------------------
  { on = "<C-y>", run = "quit", desc = "Quit Yazi" },
]
