# Title         : keymap.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/keymap.toml
# ----------------------------------------------------------------------------
# Custom keybindings for Yazi file manager

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# --- Shell Script Keybindings -----------------------------------------------
[[mgr.prepend_keymap]] # macOS: Preview files with the system Quick Look
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

# --- Script Integrated Keybindings ------------------------------------------
[[mgr.append_keymap]]
on = [ "<C-A-D-y>" ] # Super (⌘⌃⌥) + Y → focus Neovim/editor pane
run = "shell 'yazi-focus-nvim.sh'"
desc = "Focus nvim pane"

[[mgr.append_keymap]]
on = [ "<C-A-D-p>" ] # Super (⌘⌃⌥) + P → open directory in sibling Zellij pane
run = "shell 'yazi-open-dir.sh \"$0\"'"
desc = "Open directory in new pane"

[[mgr.append_keymap]]
on = [ "<C-A-D-r>" ] # Super (⌘⌃⌥) + R → reveal selection in sidebar/fullscreen Yazi
run = "shell 'yazi-reveal.sh \"$1\"'"
desc = "Reveal file in sidebar"

# --- Standard Keybindings ---------------------------------------------------
[[mgr.append_keymap]]
on = [ "<C-y>" ]
run = "quit"
desc = "Quit Yazi"
