# Title         : yazi.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/yazi.toml
# ----------------------------------------------------------------------------
# Core Yazi configuration with pane ratios and file opener integration

prepend_previewers = [
  # Archive content preview
  { name = "*.{tar,tar.gz,tar.bz2,tar.xz,tgz,tbz2,txz}", run = 'piper -- tar tf "$1"' },
  { name = "*.{7z,zip,rar}", run = 'piper -- 7zz l "$1"' },

  # Markdown preview with glow
  { name = "*.md", run = 'piper -- glow -w $w "$1"' },

  # Directory preview with eza tree mode (uses existing eza.nix Dracula theme)
  { name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]

[mgr]
ratio = [1, 4, 3]
linemode = "mtime"

[opener]
edit = [
  { run = 'yazi-open-nvim.sh "$1"', desc = "Open in Neovim" },
]
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here", for = "unix" },
]

[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc = 536870912    # 512MB - WezTerm can handle larger images efficiently
image_bound = [4096, 4096]
suppress_preload = false   # Enable preloading for better performance

[pick]
open_title = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by = "none"
sort_sensitive = false
sort_reverse = false
sort_translit = false

[input]
cursor_blink = true # Visual feedback for cursor position

# Directory navigation
cd_title = "Change directory to:"
cd_origin = "top-center"
cd_offset = [0, 3, 60, 3]

# File/directory creation
create_title = ["Create file:", "Create directory:"]
create_origin = "top-center"
create_offset = [0, 3, 60, 3]

# File renaming
rename_title = "Rename to:"
rename_origin = "hovered"
rename_offset = [0, 1, 60, 3]

# File filtering
filter_title = "Filter:"
filter_origin = "top-center"
filter_offset = [0, 3, 60, 3]

# File finding
find_title = ["Find next:", "Find previous:"]
find_origin = "top-center"
find_offset = [0, 3, 60, 3]

# Content searching
search_title = "Search via {n}:"
search_origin = "top-center"
search_offset = [0, 3, 70, 3]

# Shell command execution
shell_title = ["Shell:", "Shell (block):"]
shell_origin = "top-center"
shell_offset = [0, 3, 70, 3]

[confirm]
# Trash confirmation
trash_title = "Trash {n} selected file{s}?"
trash_origin = "center"
trash_offset = [0, 0, 70, 20]

# Delete confirmation
delete_title = "Permanently delete {n} selected file{s}?"
delete_origin = "center"
delete_offset = [0, 0, 70, 20]

# Overwrite confirmation
overwrite_title = "Overwrite file?"
overwrite_content = "Will overwrite the following file:"
overwrite_origin = "center"
overwrite_offset = [0, 0, 50, 15]

# Quit confirmation
quit_title = "Quit?"
quit_content = "The following tasks are still running, are you sure you want to quit?"
quit_origin = "center"
quit_offset = [0, 0, 50, 15]
