# Title         : yazi.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/yazi.toml
# ----------------------------------------------------------------------------
# Core Yazi configuration with pane ratios and file opener integration

[mgr]
ratio = [1, 4, 3]

[opener]
edit = [
  { run = 'yazi-open-nvim.sh "$1"', desc = "Open in Neovim" },
]
