# Title         : yazi.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : modules/home/programs/apps/yazi/yazi.toml
# ----------------------------------------------------------------------------
# Core Yazi configuration with pane ratios and file opener integration

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[plugin]
prepend_previewers = [
  { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { url = "*.csv", run = 'piper -- rich --line-numbers --force-terminal "$1"' },
  { url = "*.md", run = 'piper -- rich --line-numbers --force-terminal "$1"' },
]

[mgr]
ratio = [1, 4, 3]
sort_by = "natural"                        # Natural sort: 1.md < 2.md < 10.md (better than alphabetical)
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true                       # Better handling of international characters
linemode = "mtime"                         # Show modification time for workflow context
show_hidden = false
show_symlink = false
mouse_events = ["click", "scroll", "drag"] # Full mouse support
title_format = "Yazi: {cwd}"

[opener]
edit = [{ run = 'plugin augment-command -- editor', desc = "Open in editor" }]
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here", for = "unix" },
]

[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc = 536870912    # 512MB - WezTerm can handle larger images efficiently
image_bound = [4096, 4096]
suppress_preload = false   # Enable preloading for better performance

[pick]
open_title = " [OPEN WITH] "
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by = "none"
sort_sensitive = false
sort_reverse = false
sort_translit = false

[input]
cursor_blink = true # Visual feedback for cursor position

# Directory navigation
cd_title = " [GO TO DIR] "
cd_origin = "bottom-center"
cd_offset = [0, -3, 50, 3]

# File/directory creation
create_title = [" [CREATE FILE] ", " [CREATE DIR] "]
create_origin = "bottom-center"
create_offset = [0, -3, 50, 3]

# File renaming
rename_title = " [RENAME] "
rename_origin = "bottom-center"
rename_offset = [0, -3, 50, 3]

# File filtering
filter_title = " [FILTER] "
filter_origin = "bottom-center"
filter_offset = [0, -3, 50, 3]

# File finding
find_title = [" [FIND NEXT] ", " [FIND PREVIOUS] "]
find_origin = "bottom-center"
find_offset = [0, -3, 50, 3]

# Content searching
search_title = " [SEARCH - {n}] "
search_origin = "bottom-center"
search_offset = [0, -3, 50, 3]

# Shell command execution
shell_title = [" [SHELL] ", " [SHELL BLOCK] "]
shell_origin = "bottom-center"
shell_offset = [0, -3, 60, 3]

[confirm]
# Trash confirmation
trash_title = " [TRASH {n} FILE{s}] "
trash_origin = "center"
trash_offset = [0, 0, 50, 10]

# Delete confirmation
delete_title = " [DELETE {n} FILE{s}] "
delete_origin = "center"
delete_offset = [0, 0, 50, 10]

# Overwrite confirmation
overwrite_title = " [OVERWRITE FILE] "
overwrite_content = "Will overwrite the following file:"
overwrite_origin = "center"
overwrite_offset = [0, 0, 50, 10]

# Quit confirmation
quit_title = " [QUIT] "
quit_content = "The following tasks are still running, are you sure you want to quit?"
quit_origin = "center"
quit_offset = [0, 0, 50, 10]
