# Title         : packages.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/packages.toml
# ----------------------------------------------------------------------------
# Yazi plugin configuration - Let ya pack manage this automatically
