# Title         : packages.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/packages.toml
# ----------------------------------------------------------------------------
# Yazi plugin configuration - managed by ya pkg commands

# Core functionality plugins
[[plugin.deps]]
use = "yazi-rs/plugins:session"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:smart-paste"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:mactag"
rev = ""
hash = ""

# Navigation plugins
[[plugin.deps]]
use = "yazi-rs/plugins:smart-enter"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:jump-to-char"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = ""
hash = ""

[[plugin.deps]]
use = "Rolv-Apneseth/bypass"
rev = ""
hash = ""

# UI enhancements
[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = ""
hash = ""

# Development plugins
[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:diff"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:mime-ext"
rev = ""
hash = ""

# Archive support
[[plugin.deps]]
use = "yazi-rs/plugins:lsar"
rev = ""
hash = ""

# Essential third-party plugins
[[plugin.deps]]
use = "Reledia/glow.yazi"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:zoom"
rev = ""
hash = ""

# Starship integration for rich prompt display
[[plugin.deps]]
use = "Rolv-Apneseth/starship.yazi"
rev = ""
hash = ""

# File preview enhancements
[[plugin.deps]]
use = "yazi-rs/plugins:miller"
rev = ""
hash = ""

[[plugin.deps]]
use = "yazi-rs/plugins:hexyl"
rev = ""
hash = ""
