# Title         : theme.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/yazi/theme.toml
# ----------------------------------------------------------------------------
# Consolidated Dracula theme with custom icons

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Dracula Color Palette
# Background: #282a36, Current Line: #44475a, Selection: #44475a
# Foreground: #f8f8f2, Comment: #6272a4
# Cyan: #8be9fd, Green: #50fa7b, Orange: #ffb86c
# Pink: #ff79c6, Purple: #bd93f9, Red: #ff5555, Yellow: #f1fa8c

# SEMANTIC COLOR SYSTEM
# =====================
# PRIMARY INTERACTION - Purple (#bd93f9): Active states, main selections, elevated components
# SUCCESS/CONFIRMATION - Green (#50fa7b): Success states, positive actions, development files
# ATTENTION/HIGHLIGHT - Yellow (#f1fa8c): CWD, search highlights, system/config files
# DANGER/DESTRUCTIVE - Red (#ff5555): Errors, destructive actions, warnings
# INFORMATION/SECONDARY - Cyan (#8be9fd): Secondary actions, metadata, data files
# ACCENT/CREATIVE - Pink (#ff79c6): Special highlights, creative/media content
# NEUTRAL/SUBDUED - Comment (#6272a4): Less important elements, separators
# STRUCTURE/BORDERS - Current Line (#44475a): Borders for inline components

# Dracula Color Palette
# Background: #282a36
# Selection: #44475a
# Foreground: #f8f8f2
# Blue: #6272a4
# Cyan: #8be9fd
# Green: #50fa7b
# Orange: #ffb86c
# Pink: #ff79c6
# Purple: #bd93f9
# Red: #ff5555
# Yellow: #f1fa8c

[mgr] # Done
cwd = { fg = "#f1fa8c", underline = true }
hovered = { fg = "#282a36", bg = "#f8f8f2", bold = true }
preview_hovered = { fg = "#f8f8f2", underline = true }
find_keyword = { fg = "#282a36", bg = "#f1fa8c", bold = true }
find_position = { fg = "#282a36", bg = "#ffb86c", bold = true }
symlink_target = { fg = "#ff5555", bold = true }
marker_marked = { fg = "#282a36", bg = "#bd93f9", bold = true }
marker_copied = { fg = "#282a36", bg = "#ffb86c", bold = true }
marker_cut = { fg = "#282a36", bg = "#ff5555", bold = true }
marker_selected = { fg = "#282a36", bg = "#8be9fd", bold = true }
count_copied = { fg = "#282a36", bg = "#ffb86c", bold = true }
count_cut = { fg = "#282a36", bg = "#ff5555", bold = true }
count_selected = { fg = "#282a36", bg = "#8be9fd", bold = true }
border_symbol = "│"
border_style = { fg = "#44475a" }
syntect_theme = ""

[tabs] # Done
active = { fg = "#282a36", bg = "#8be9fd", bold = true }
inactive = { fg = "#f8f8f2", bg = "#6272a4" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode] # Done
normal_main = { fg = "#282a36", bg = "#50fa7b", bold = true }
normal_alt = { fg = "#f8f8f2", bg = "#44475a", bold = true }
select_main = { fg = "#282a36", bg = "#bd93f9", bold = true }
select_alt = { fg = "#f8f8f2", bg = "#44475a", bold = true }
unset_main = { fg = "#282a36", bg = "#ff5555", bold = true }
unset_alt = { fg = "#f8f8f2", bg = "#44475a", bold = true }

[status] # Done
overall = { bg = "#282a36" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
perm_type = { fg = "#50fa7b" }
perm_read = { fg = "#ffb86c" }
perm_write = { fg = "#f8f8f2" }
perm_exec = { fg = "#ff5555" }
perm_sep = { fg = "#8be9fd" }
progress_label = { fg = "#282a36", bold = true }
progress_normal = { fg = "#50fa7b", bg = "#282a36" }
progress_error = { fg = "#ff5555", bg = "#282a36" }

[which] # Done
cols = 3
mask = { bg = "#282a36" }
cand = { fg = "#8be9fd" }
rest = { fg = "#50fa7b" }
desc = { fg = "#f8f8f2" }
separator = ""
separator_style = { fg = "#f1fa8c" }

[confirm] # Done
border = { fg = "#8be9fd" }
title = { fg = "#8be9fd", bold = true }
content = { fg = "#f8f8f2" }
list = {}
btn_yes = { fg = "#50fa7b", bg = "#282a36", bold = true }
btn_no = { fg = "#ff5555", bg = "#282a36", bold = true }
btn_labels = ["[YES]", "[NO]"]

[spot] # Done
border = { fg = "#8be9fd" }
title = { fg = "#8be9fd", bold = true }
tbl_col = { fg = "#8be9fd" }
tbl_cell = { fg = "#f8f8f2", reversed = true }

[notify]
title_info = { fg = "#50fa7b" }
title_warn = { fg = "#f1fa8c" }
title_error = { fg = "#ff5555" }
icon_info = ""
icon_warn = ""
icon_error = ""

[pick]
border = { fg = "#8be9fd" }
active = { fg = "#ff79c6", bold = true }
inactive = {}

[input]
border = { fg = "#8be9fd" }
title = { fg = "#8be9fd", bold = true }
value = { fg = "#f8f8f2" }
selected = { bg = "#44475a" }

[cmp]
border = { fg = "#8be9fd" }
active = { fg = "#282a36", bg = "#f8f8f2", bold = true }
# inactive = { fg = "#f8f8f2" }
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#8be9fd" }
title = { fg = "#8be9fd", bold = true }
hovered = { fg = "#282a36", bg = "#f8f8f2" }

[help] # Done
on = { fg = "#50fa7b", bold = true }
run = { fg = "#8be9fd" }
desc = { fg = "#f8f8f2" }
hovered = { fg = "#282a36", bg = "#6272a4" }
footer = { fg = "#f1fa8c" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#ff79c6" },
  # Videos and Audio
  { mime = "video/*", fg = "#bd93f9" },
  { mime = "audio/*", fg = "#bd93f9" },
  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f1fa8c" },
  # Documents
  { mime = "application/pdf", fg = "#ff5555" },
  # Empty files
  { mime = "inode/empty", fg = "#8be9fd" },
  # Programming languages
  { name = "*.py", fg = "#50fa7b" },
  { name = "*.js", fg = "#f1fa8c" },
  { name = "*.ts", fg = "#8be9fd" },
  { name = "*.jsx", fg = "#8be9fd" },
  { name = "*.tsx", fg = "#8be9fd" },
  { name = "*.rs", fg = "#ff79c6" },
  { name = "*.go", fg = "#8be9fd" },
  { name = "*.nix", fg = "#8be9fd" },
  # Configuration files
  { name = "*.{json,toml,yaml,yml,xml}", fg = "#bd93f9" },
  # Web files
  { name = "*.{html,css,scss}", fg = "#ff79c6" },
  # Documentation
  { name = "*.md", fg = "#f8f8f2" },
  { name = "README*", fg = "#50fa7b", bold = true },
  { name = "LICENSE*", fg = "#50fa7b", bold = true },
  # 3D Parametric & Technical Design
  { name = "*.{3dm,3dmbak,gh,ghx}", fg = "#8be9fd" },
  # CAD/Engineering/Architecture
  { name = "*.{dwg,dxf,dwt,rvt,rfa,rft}", fg = "#bd93f9" },
  # Creative 3D Modeling
  { name = "*.{blend,blend1}", fg = "#ff79c6" },
  # Adobe Creative Suite
  { name = "*.{psd,psb,ai,ait,indd,idml,indt}", fg = "#ff79c6" },
  # Shell scripts
  { name = "*.sh", fg = "#50fa7b" },
  { name = "*Dockerfile*", fg = "#8be9fd" },
  { name = "Makefile", fg = "#ff79c6" },
  # Logs
  { name = "*.log", fg = "#6272a4" },
  # Special files
  { name = "*", is = "orphan", fg = "#ff5555" },
  { name = "*", is = "exec", fg = "#50fa7b" },
  { name = "*", is = "dummy", bg = "#ff5555" },
  { name = "*/", is = "dummy", bg = "#ff5555" },
  # Fallback
  { name = "*/", fg = "#8be9fd", bold = true },
]

[icon]
prepend_dirs = [
  { name = ".git", text = "󰊢", fg = "#ff79c6" },
  { name = "node_modules", text = "󰏗", fg = "#50fa7b" },
  { name = "target", text = "󰀘", fg = "#ff79c6" },
  { name = ".venv", text = "󰅩", fg = "#f1fa8c" },
  { name = "__pycache__", text = "󰌠", fg = "#f1fa8c" },
  { name = ".config", text = "", fg = "#bd93f9" },
  { name = ".ssh", text = "", fg = "#ff79c6" },
  { name = "src", text = "󰈙", fg = "#8be9fd" },
  { name = "bin", text = "󰞰", fg = "#50fa7b" },
]

prepend_exts = [
  { name = "nix", text = "󱄅", fg = "#8be9fd" },
  { name = "py", text = "󰌠", fg = "#f1fa8c" },
  { name = "rs", text = "", fg = "#ff79c6" },
  { name = "js", text = "", fg = "#f1fa8c" },
  { name = "ts", text = "", fg = "#8be9fd" },
  { name = "go", text = "", fg = "#8be9fd" },
  { name = "lua", text = "", fg = "#8be9fd" },
  { name = "jsx", text = "", fg = "#8be9fd" },
  { name = "tsx", text = "", fg = "#8be9fd" },
  # Configuration & Data
  { name = "json", text = "", fg = "#bd93f9" },
  { name = "toml", text = "", fg = "#bd93f9" },
  { name = "yaml", text = "", fg = "#bd93f9" },
  { name = "yml", text = "", fg = "#bd93f9" },
  { name = "xml", text = "", fg = "#bd93f9" },
  { name = "env", text = "", fg = "#f1fa8c" },
  { name = "gitignore", text = "", fg = "#ff79c6" },
  # Web
  { name = "html", text = "", fg = "#ff79c6" },
  { name = "css", text = "", fg = "#8be9fd" },
  { name = "scss", text = "", fg = "#ff79c6" },
  # Shell & Scripts
  { name = "sh", text = "", fg = "#50fa7b" },
  { name = "bash", text = "", fg = "#50fa7b" },
  # Documentation
  { name = "md", text = "", fg = "#f8f8f2" },
  { name = "pdf", text = "", fg = "#ff5555" },
  # Office Documents
  { name = "doc", text = "", fg = "#8be9fd" },
  { name = "docx", text = "", fg = "#8be9fd" },
  { name = "xls", text = "", fg = "#50fa7b" },
  { name = "xlsx", text = "", fg = "#50fa7b" },
  { name = "ppt", text = "", fg = "#ff5555" },
  { name = "pptx", text = "", fg = "#ff5555" },
  # Images
  { name = "svg", text = "󰜡", fg = "#ff79c6" },
  { name = "jpg", text = "", fg = "#ff79c6" },
  { name = "jpeg", text = "", fg = "#ff79c6" },
  { name = "png", text = "", fg = "#ff79c6" },
  { name = "tiff", text = "", fg = "#ff79c6" },
  { name = "tif", text = "", fg = "#ff79c6" },
  # Archives
  { name = "zip", text = "", fg = "#f1fa8c" },
  { name = "tar", text = "", fg = "#f1fa8c" },
  { name = "gz", text = "", fg = "#f1fa8c" },
  { name = "7z", text = "", fg = "#f1fa8c" },
  # Database
  { name = "sql", text = "", fg = "#ffb86c" },
  { name = "db", text = "", fg = "#ffb86c" },
  { name = "sqlite", text = "", fg = "#ffb86c" },
  # 3D Parametric & Technical Design
  { name = "3dm", text = "", fg = "#8be9fd" },
  { name = "3dmbak", text = "", fg = "#8be9fd" },
  { name = "gh", text = "󰮄", fg = "#8be9fd" },
  { name = "ghx", text = "󰮄", fg = "#8be9fd" },
  # CAD/Engineering/Architecture
  { name = "dwg", text = "󰕡", fg = "#bd93f9" },
  { name = "dxf", text = "󰕡", fg = "#bd93f9" },
  { name = "dwt", text = "󰕡", fg = "#bd93f9" },
  { name = "rvt", text = "󰕡", fg = "#bd93f9" },
  { name = "rfa", text = "󰕡", fg = "#bd93f9" },
  { name = "rft", text = "󰕡", fg = "#bd93f9" },
  # Creative 3D Modeling
  { name = "blend", text = "", fg = "#ff79c6" },
  { name = "blend1", text = "", fg = "#ff79c6" },
  # Adobe Creative Suite
  { name = "psd", text = "", fg = "#ff79c6" },
  { name = "psb", text = "", fg = "#ff79c6" },
  { name = "ai", text = "", fg = "#bd93f9" },
  { name = "ait", text = "", fg = "#bd93f9" },
  { name = "indd", text = "󰲋", fg = "#ffb86c" },
  { name = "idml", text = "󰲋", fg = "#ffb86c" },
  { name = "indt", text = "󰲋", fg = "#ffb86c" },
  # Photography & Asset Management
  { name = "lrcat", text = "󰄄", fg = "#f1fa8c" },
  { name = "lrtemplate", text = "󰄄", fg = "#f1fa8c" },
  { name = "xmp", text = "󰄄", fg = "#f1fa8c" },
]

prepend_conds = [
  { if = "hidden & dir", text = "󰘓" },
  { if = "hidden & !dir", text = "󰟦" },
  { if = "link & !orphan", text = "" },
  { if = "orphan", text = "󰈂" },
]
