# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/apps/broot/config.toml
# ----------------------------------------------------------------------------
# Broot interactive tree configuration with Dracula theme

modal = true

[skin]
# --- Dracula Theme Colors ------------------------------------------------
status_normal_fg = "#f8f8f2" # Foreground
status_normal_bg = "#44475a" # Current Line
status_error_fg = "#ff5555"  # Red
status_error_bg = "#282a36"  # Background
# Tree colors
tree_fg = "#f8f8f2"          # Foreground
selected_line_bg = "#44475a" # Current Line
permissions_fg = "#6272a4"   # Comment
# Progress bars
size_bar_full_bg = "#50fa7b" # Green
size_bar_void_bg = "#282a36" # Background
# File type colors
directory_fg = "#8be9fd" # Cyan
exe_fg = "#50fa7b"       # Green
link_fg = "#ff79c6"      # Pink
# Input and UI
input_fg = "#8be9fd"        # Cyan
flag_value_fg = "#f1fa8c"   # Yellow
table_border_fg = "#6272a4" # Comment
code_fg = "#f1fa8c"         # Yellow
# Additional Dracula colors
file_fg = "#f8f8f2"    # Normal files
pruning_fg = "#ff5555" # Red for pruned/excluded
# Git status colors
git_status_new_fg = "#50fa7b"      # Green
git_status_modified_fg = "#ffb86c" # Orange
git_status_deleted_fg = "#ff5555"  # Red

# --- Verbs (Actions) -----------------------------------------------------
[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
invocation = "view"
shortcut = "v"
execution = "bat {file}"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
leave_broot = false

# Git operations
[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

[[verbs]]
invocation = "git_status"
shortcut = "gs"
execution = "git status {directory}"

[[verbs]]
invocation = "git_log"
shortcut = "gl"
execution = "git log {file}"

# Navigation shortcuts
[[verbs]]
invocation = "home"
key = "ctrl-h"
execution = ":focus ~"

[[verbs]]
invocation = "root"
key = "ctrl-r"
execution = ":focus /"

[[verbs]]
invocation = "parent"
shortcut = "p"
execution = ":parent"

# Directory operations
[[verbs]]
invocation = "mkdir {subpath}"
shortcut = "md"
execution = "mkdir -p {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "cd"
key = "alt-enter"
execution = "cd {directory}"
from_shell = true

# Copy to other panel
[[verbs]]
invocation = "copy_to_panel"
shortcut = "cpp"
execution = "cp -r {file} {other-panel-directory}"
apply_to = "any"

[[verbs]]
invocation = "move_to_panel"
shortcut = "mvp"
execution = "mv {file} {other-panel-directory}"
apply_to = "any"
