# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/apps/codex/config.toml
# ----------------------------------------------------------------------------
# ChatGPT Codex configurations

# --- Codex Defaults ---------------------------------------------------------
preferred_auth_method = "chatgpt"
model = "gpt-5"
approval_policy = "on-request"                                                                          # ask before running edits/commands
sandbox_mode = "workspace-write"                                                                        # read-all, write under CWD
disable_response_storage = true                                                                         # helpful for ZDR orgs
projects = { "/Users/bardiasamiee/Documents/99.Github/Parametric_Forge" = { trust_level = "trusted" } }
