# Title         : config.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/apps/codex/config.toml
# ----------------------------------------------------------------------------
# ChatGPT Codex configurations

# --- Codex Defaults ---------------------------------------------------------
preferred_auth_method = "chatgpt"
model = "gpt-5"
approval_policy = "on-request"                                                                          # ask before running edits/commands
sandbox_mode = "workspace-write"                                                                        # read-all, write under CWD
projects = { "/Users/bardiasamiee/Documents/99.Github/Parametric_Forge" = { trust_level = "trusted" } }

[mcp_servers.filesystem]
type = "stdio"
command = "npx"
args = ["@modelcontextprotocol/server-filesystem", "/Users/bardiasamiee"]
env = {}

[mcp_servers.github]
type = "stdio"
command = "npx"
args = ["@modelcontextprotocol/server-github"]
env = { GITHUB_TOKEN = "${GITHUB_TOKEN}" }

[mcp_servers.perplexity]
type = "stdio"
command = "npx"
args = ["-y", "server-perplexity-ask"]
env = { PERPLEXITY_API_KEY = "${PERPLEXITY_API_KEY}" }

[mcp_servers.tavily]
type = "stdio"
command = "npx"
args = ["-y", "tavily-mcp@0.1.3"]
env = { TAVILY_API_KEY = "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" }

[mcp_servers.exa]
type = "stdio"
command = "npx"
args = ["-y", "exa-mcp-server"]
env = { EXA_API_KEY = "a5c925cb-b57c-4cd4-abbc-050a56e39f0d" }

[mcp_servers.context7]
type = "stdio"
command = "npx"
args = ["@upstash/context7-mcp"]
env = {}
