# Title         : .stylua.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/languages/.stylua.toml
# ----------------------------------------------------------------------------

# --- Core Formatting Configuration ------------------------------------------
# Core formatting (unified 4-space indentation)
indent_type = "Spaces"              # Use spaces instead of tabs
indent_width = 4                    # 4-space indentation (unified project standard)
column_width = 120                  # 120-char line width (matches project standard)
quote_style = "AutoPreferDouble"    # Prefer double quotes consistently
call_parentheses = "Always"         # Always use parentheses for function calls
collapse_simple_statement = "Never" # Never collapse statements for clarity

# --- Module Organization ---------------------------------------------------
[sort_requires]
enabled = true # Sort require statements alphabetically
