# Title         : cargo.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : /01.home/00.core/configs/languages/cargo.toml
# ----------------------------------------------------------------------------
# Cargo global configuration (CARGO_HOME/config.toml)

[build]
jobs = 0 # 0 = use all available CPU cores

# --- Network Configuration ---------------------------------------------------
[http]
timeout = 30 # HTTP timeout in seconds

[net]
retry = 3                 # Network retry attempts
git-fetch-with-cli = true # Use git CLI for fetches (better auth handling)

[registries.crates-io]
protocol = "sparse" # Use sparse protocol for faster index updates
