# Title         : nil.toml
# Author        : Bardia Samiee
# Project       : Parametric Forge
# License       : MIT
# Path          : 01.home/00.core/configs/languages/nil.toml
# ----------------------------------------------------------------------------
# Nix LSP configuration

# --- Formatting Configuration -----------------------------------------------
[formatting]
command = ["nixfmt"]

# --- Diagnostics Configuration ---------------------------------------------
[diagnostics]
excludedFiles = ["flake.lock", "*.patch"]

# --- Nix Configuration -----------------------------------------------------
[nix]
binary = "nix"

# --- Flake Configuration ---------------------------------------------------
[flake]
autoEvalInputs = false
